### ISSUE TITLE
After building qa, start_qa.sh errors out with "Could not find or load main class QADaemon"

### ISSUE THREAD

**Issue by ryanniehaus** [claritylab/lucida#101]
compiled in lucida/lucida/qa/lucida/

**Comment by cdmeister** [comment]
Was there a bunch of compiling errors that were related to thrift by any chance?

**Comment by ryanniehaus** [comment]
Oh yeah... somehow I missed that.

I get a bunch of  "error: package org.apache.thrift does not exist"
is there a classpath or something that needs to be set?

**Comment by cdmeister** [comment]
So, you need to download thrift v9.2 and compile only java stuff via ant. And then you have to link the thrift jar file that is produced via ant in one of the configure scripts to make qa compile.

I am not sure if this is documented, but its kinda of annoying. Let me know if you are still having trouble.

**Comment by ryanniehaus** [comment]
Please see pull request #103 for better qa build instructions

**Comment by ryanniehaus** [comment]
Thanks for the help.  I was able to get this working now.  Very cool work you've done here.
I've even built my own index to experiment with.

One question:  In the promo video, I saw a GUI.  Is the GUI code included somewhere?  I'm not seeing it.  It'd make things a little easier to play around with it.

**Comment by JeremyARussell** [comment]
I can field that one :) Check it out here at https://github.com/claritylab/clarity-mobile

I've started dabbling with getting it working but I think I'm running into errors on my first Ubuntu Lucida VM because I kind of used the new Thrift 0.9.3 instead of 0.9.2.. If you end up diving into it yourself drop me a line and maybe we can investigate together.

**Comment by jhauswald** [comment]
We're giving a tutorial next week in Barcelona (check out [lucida.ai](lucida.ai)) at a conference and we'll probably have a browser front-end by then. Although as @JeremyARussell pointed out there is one, it just needs a little work ;)
