### ISSUE TITLE
[dev] High Level Issues/Comments

### ISSUE THREAD

**Issue by jhauswald** [claritylab/lucida#113]
As of a37daa626a4dc78f7dc9ea8a745aae17a8ae1a15
**Issues**:
- All new services should be integrated into the build system and should pass continuous integration
- OpenEphyra doesn't build, needs a Makefile.
- `thrift-gen.sh` breaks because OpenEphyra was renamed
- calendar service readme looks somewhat confusing
- OpenEphyra has some autogenerated thrift source committed, should be removed. Only generate at runtime.

**Questions**:
- IMM seems incomplete (confirm?) 
- how is Kaldi supposed to be built? Source seems to be removed.
- Need documentation to teach how to hook into build system and how each service should use/generate thrift files. Ideally all services use the same thrift generated files. Generate their own depending on the language its written in.
- build system looks completely broken. [needs revert]
- learn service should be removed
- `.thrift` files have been copied everywhere, these should be generated once either for all the services or subclassed and then generated. See the build system.
- each service should have a very simple python client showing the functionality
- Register to command center can work like this:
  - try to register, if it can't (catch exception from thrift) just open server and run stand-alone.

We need a status with for each service if its done. Done means:
- Create, Learn, Infer (when applicable)
- Integrated in build system and passes continuous integration
- has a simple (python?) client for standalone testing
- has register function for command center
- sample data to integrate into new command center with query pipeline description.
- READMEs done

@haoyifan @yunshengb

**Comment by yunshengb** [comment]
"OpenEphyra doesn't build, needs a Makefile." Please read lucida/lucida/questionanswering/README.md: "Navigate to OpenEphyra, ./compile-OpenEphyra.sh" should build OpenEphyra. Please understand that OpenEphyra isn't written in C/C++, and Apache Ant is used as the build system of OpenEphyra.

**Comment by yunshengb** [comment]
"OpenEphyra has some autogenerated thrift source committed, should be removed. Only generate at runtime." Please notice that the first line of lucida/lucida/questionanswering/OpenEphyra/src/lucida/thrift/LucidaService.java is "package lucida.thrift;" which is added manually because of Java's building rules. Automatically generated thrift source code does not have that line.
