### ISSUE TITLE
no space left on device with docker pull claritylab/lucida:latest

### ISSUE THREAD

**Issue by cwpearson** [claritylab/lucida#119]
Running `sudo docker pull claritylab/lucida:latest` yields

`failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /usr/local/lucida/lucida/speechrecognition/common/src/gmmbin/gmm-rescore-lattice: no space left on device`

when extracting the final pull.

`uname -a` = `Linux rigel 4.5.7-040507-generic #201606100436 SMP Fri Jun 10 08:38:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

`sudo docker version` = 

    Client:
     Version:      1.11.2
     API version:  1.23
     Go version:   go1.5.4
     Git commit:   b9f10c9
     Built:        Wed Jun  1 22:00:43 2016
     OS/Arch:      linux/amd64

    Server:
     Version:      1.11.2
     API version:  1.23
     Go version:   go1.5.4
     Git commit:   b9f10c9
     Built:        Wed Jun  1 22:00:43 2016
     OS/Arch:      linux/amd64

**Comment by MusicalCreeper01** [comment]
`no space left on device`

Do you have enough space left on your disk? With `df -i` you can check how much space on the partition is being used :)

**Comment by cwpearson** [comment]
:) believe it or not, I thought of that. Probably should have posted the output as well. As  I understand it, docker images are stored in `/var/lib/docker` on Ubuntu.

    $ df -h /var/lib/docker/
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/nvme0n1p7  217G   63G  143G  31% /
 
So it seems like there should be enough room, at least for now. And I have been able to successfully `docker pull claritylab/lucida-asr` for example.

**Comment by cwpearson** [comment]
This issue seems to be no longer relevant given the new docker instructions in 452eedd

**Comment by diegogrecco** [comment]
+1

**Comment by yunshengb** [comment]
It needs 16 GB of disk space as mentioned [here](https://github.com/claritylab/lucida/tree/master/tools/deploy), half of which is Kaldi ASR and its models.

**Comment by diegogrecco** [comment]
Data Space Available: 97.87 GB

**Comment by yunshengb** [comment]
1. What is your docker version? This is mine:

```yba@ubuntu:~$ sudo docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

2. Can you run a hello-world example: `sudo docker run hello-world`?

Thanks!

**Comment by diegogrecco** [comment]
[root@ol7 ~]# docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

**Comment by yunshengb** [comment]
[The README](https://github.com/claritylab/lucida/tree/master/tools/deploy) has been updated for this. Thank you!
