### ISSUE TITLE
Getting make local error

### ISSUE THREAD

**Issue by prakharnigam** [claritylab/lucida#121]
Err http://security.ubuntu.com trusty-security InRelease
  
Err http://extras.ubuntu.com trusty InRelease
  
Err http://ppa.launchpad.net trusty InRelease
  
Err http://ppa.launchpad.net trusty InRelease
  
Err http://repo.mongodb.org trusty/mongodb-org/3.2 InRelease
  
Err http://extras.ubuntu.com trusty Release.gpg
  Could not resolve 'extras.ubuntu.com'
Err http://repo.mongodb.org trusty/mongodb-org/3.2 Release.gpg
  Could not resolve 'repo.mongodb.org'
Err http://security.ubuntu.com trusty-security Release.gpg
  Could not resolve 'security.ubuntu.com'
Err http://ppa.launchpad.net trusty Release.gpg
  Could not resolve 'ppa.launchpad.net'
Err http://ppa.launchpad.net trusty Release.gpg
  Could not resolve 'ppa.launchpad.net'
Err http://in.archive.ubuntu.com trusty InRelease
  
Err http://in.archive.ubuntu.com trusty-updates InRelease
  
Err http://in.archive.ubuntu.com trusty-backports InRelease
  
Err http://in.archive.ubuntu.com trusty Release.gpg
  Could not resolve 'in.archive.ubuntu.com'
Err http://in.archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'in.archive.ubuntu.com'
Err http://in.archive.ubuntu.com trusty-backports Release.gpg
  Could not resolve 'in.archive.ubuntu.com'
Reading package lists... Done
W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/trusty-backports/InRelease  

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/InRelease  

W: Failed to fetch http://extras.ubuntu.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://repo.mongodb.org/apt/ubuntu/dists/trusty/mongodb-org/3.2/InRelease  

W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'security.ubuntu.com'

W: Failed to fetch http://extras.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'extras.ubuntu.com'

W: Failed to fetch http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu/dists/trusty/Release.gpg  Could not resolve 'ppa.launchpad.net'

W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/Release.gpg  Could not resolve 'ppa.launchpad.net'

W: Failed to fetch http://repo.mongodb.org/apt/ubuntu/dists/trusty/mongodb-org/3.2/Release.gpg  Could not resolve 'repo.mongodb.org'

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'in.archive.ubuntu.com'

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'in.archive.ubuntu.com'

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/trusty-backports/Release.gpg  Could not resolve 'in.archive.ubuntu.com'

W: Some index files failed to download. They have been ignored, or old ones used instead.
ln: failed to create symbolic link ‘/usr/local/bin/pip’: File exists
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ant is already the newest version.
autoconf is already the newest version.
automake is already the newest version.
bc is already the newest version.
bison is already the newest version.
g++ is already the newest version.
gawk is already the newest version.
gcc is already the newest version.
gfortran is already the newest version.
libblas-dev is already the newest version.
libblas3 is already the newest version.
libboost-dev is already the newest version.
libgflags-dev is already the newest version.
libgoogle-glog-dev is already the newest version.
libiberty-dev is already the newest version.
liblapack-dev is already the newest version.
liblapack3 is already the newest version.
libleveldb-dev is already the newest version.
liblzma-dev is already the newest version.
libprotoc-dev is already the newest version.
libsasl2-dev is already the newest version.
libsnappy-dev is already the newest version.
libtool is already the newest version.
make is already the newest version.
pkg-config is already the newest version.
python-gobject-2 is already the newest version.
swig is already the newest version.
vim is already the newest version.
zip is already the newest version.
zlib1g-dev is already the newest version.
autoconf-archive is already the newest version.
libatlas-base-dev is already the newest version.
libatlas-dev is already the newest version.
libatlas3-base is already the newest version.
libboost-all-dev is already the newest version.
libdouble-conversion-dev is already the newest version.
libhdf5-serial-dev is already the newest version.
libjemalloc-dev is already the newest version.
liblz4-dev is already the newest version.
libopenblas-dev is already the newest version.
libsox-dev is already the newest version.
libtesseract-dev is already the newest version.
sox is already the newest version.
supervisor is already the newest version.
binutils-dev is already the newest version.
curl is already the newest version.
flac is already the newest version.
git is already the newest version.
imagemagick is already the newest version.
libc6 is already the newest version.
libevent-dev is already the newest version.
libkrb5-dev is already the newest version.
libnuma-dev is already the newest version.
libssl-dev is already the newest version.
python-gi is already the newest version.
python-gobject is already the newest version.
python-numpy is already the newest version.
python2.7-dev is already the newest version.
scons is already the newest version.
software-properties-common is already the newest version.
subversion is already the newest version.
unzip is already the newest version.
wget is already the newest version.
python-pip is already the newest version.
cmake is already the newest version.
The following extra packages will be installed:
  libfl-dev liblmdb0
The following packages will be upgraded:
  flex libfl-dev liblmdb-dev liblmdb0
4 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
Need to get 463 kB of archives.
After this operation, 793 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  flex libfl-dev liblmdb-dev liblmdb0
E: There are problems and -y was used without --force-yes
Cannot fetch index base URL https://pypi.python.org/simple/
Could not find any downloads that satisfy the requirement distribute in /usr/local/lib/python2.7/dist-packages
Downloading/unpacking distribute
Cleaning up...
No distributions at all found for distribute in /usr/local/lib/python2.7/dist-packages
Storing debug log for failure in /.pip/pip.log
Cannot fetch index base URL https://pypi.python.org/simple/
Could not find any downloads that satisfy the requirement pip in /usr/lib/python2.7/dist-packages
Downloading/unpacking pip
Cleaning up...
No distributions at all found for pip in /usr/lib/python2.7/dist-packages
Storing debug log for failure in /.pip/pip.log
Requirement already satisfied (use --upgrade to upgrade): Flask==0.10.1 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Flask-Login==0.3.2 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): Flask-WTF==0.12 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): WTForms==2.1 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.4 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): argparse==1.2.1 in /usr/lib/python2.7 (from -r python_requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): backports-abc==0.4 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname==3.5.0.1 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): cached-property==1.3.0 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): certifi==2016.2.28 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): config==0.3.9 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): defer==1.0.3 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): docker-compose==1.7.1 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): docker-py==1.8.1 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): dockerpty==0.4.1 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.2 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): functools32==3.2.3-2 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): futures==3.0.5 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 20))
Requirement already satisfied (use --upgrade to upgrade): greenlet==0.4.9 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): html5lib==0.999 in /usr/lib/python2.7/dist-packages (from -r python_requirements.txt (line 22))
Requirement already satisfied (use --upgrade to upgrade): httplib2==0.8 in /usr/lib/python2.7/dist-packages (from -r python_requirements.txt (line 23))
Requirement already satisfied (use --upgrade to upgrade): ipaddress==1.0.16 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 24))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 25))
Requirement already satisfied (use --upgrade to upgrade): jsonlib2==1.5.2 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 26))
Requirement already satisfied (use --upgrade to upgrade): jsonschema==2.5.1 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 27))
Requirement already satisfied (use --upgrade to upgrade): oauthlib==0.6.1 in /usr/lib/python2.7/dist-packages (from -r python_requirements.txt (line 28))
Requirement already satisfied (use --upgrade to upgrade): piston-mini-client==0.7.5 in /usr/lib/python2.7/dist-packages (from -r python_requirements.txt (line 29))
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL==0.13 in /usr/lib/python2.7/dist-packages (from -r python_requirements.txt (line 30))
Requirement already satisfied (use --upgrade to upgrade): pycrypto==2.6.1 in /usr/lib/python2.7/dist-packages (from -r python_requirements.txt (line 31))
Requirement already satisfied (use --upgrade to upgrade): pymongo==3.2.2 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 32))
Requirement already satisfied (use --upgrade to upgrade): pyserial==2.6 in /usr/lib/python2.7/dist-packages (from -r python_requirements.txt (line 33))
Requirement already satisfied (use --upgrade to upgrade): pysha3==0.3 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 34))
Requirement already satisfied (use --upgrade to upgrade): python-dateutil==2.5.3 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 35))
Requirement already satisfied (use --upgrade to upgrade): pytz==2016.4 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 36))
Requirement already satisfied (use --upgrade to upgrade): pyxdg==0.25 in /usr/lib/python2.7/dist-packages (from -r python_requirements.txt (line 37))
Requirement already satisfied (use --upgrade to upgrade): rauth==0.7.2 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 38))
Requirement already satisfied (use --upgrade to upgrade): reportlab==3.0 in /usr/lib/python2.7/dist-packages (from -r python_requirements.txt (line 39))
Requirement already satisfied (use --upgrade to upgrade): requests==2.7.0 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 40))
Requirement already satisfied (use --upgrade to upgrade): scipy==0.17.1 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 41))
Requirement already satisfied (use --upgrade to upgrade): singledispatch==3.4.0.3 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 42))
Requirement already satisfied (use --upgrade to upgrade): six==1.5.2 in /usr/lib/python2.7/dist-packages (from -r python_requirements.txt (line 43))
Requirement already satisfied (use --upgrade to upgrade): supervisor==3.0b2 in /usr/lib/python2.7/dist-packages (from -r python_requirements.txt (line 44))
Requirement already satisfied (use --upgrade to upgrade): texttable==0.8.4 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 45))
Requirement already satisfied (use --upgrade to upgrade): thrift==0.9.3 in /usr/local/lib/python2.7/dist-packages/thrift-0.9.3-py2.7-linux-x86_64.egg (from -r python_requirements.txt (line 46))
Requirement already satisfied (use --upgrade to upgrade): tornado==4.3 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 47))
Requirement already satisfied (use --upgrade to upgrade): torthrift==0.0.9 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 48))
Requirement already satisfied (use --upgrade to upgrade): urllib3==1.7.1 in /usr/lib/python2.7/dist-packages (from -r python_requirements.txt (line 49))
Requirement already satisfied (use --upgrade to upgrade): virtualenv==15.0.1 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 50))
Requirement already satisfied (use --upgrade to upgrade): websocket-client==0.37.0 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 51))
Requirement already satisfied (use --upgrade to upgrade): wheel==0.24.0 in /usr/lib/python2.7/dist-packages (from -r python_requirements.txt (line 52))
Requirement already satisfied (use --upgrade to upgrade): ws4py==0.3.2 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 53))
Requirement already satisfied (use --upgrade to upgrade): scikit-learn==0.17.1 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 54))
Requirement already satisfied (use --upgrade to upgrade): numpy==1.8.2 in /usr/lib/python2.7/dist-packages (from -r python_requirements.txt (line 55))
Requirement already satisfied (use --upgrade to upgrade): pandas==0.18.1 in /usr/local/lib/python2.7/dist-packages (from -r python_requirements.txt (line 56))
Requirement already satisfied (use --upgrade to upgrade): PyYAML<4,>=3.10 in /usr/local/lib/python2.7/dist-packages (from docker-compose==1.7.1->-r python_requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): enum34<2,>=1.0.4 in /usr/local/lib/python2.7/dist-packages (from docker-compose==1.7.1->-r python_requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): meld3>=0.6.5 in /usr/lib/python2.7/dist-packages (from supervisor==3.0b2->-r python_requirements.txt (line 44))
Cleaning up...
(sudo ./install_java.sh) || (exit 1)
Cannot add PPA: 'ppa:webupd8team/java'.
Please check that the PPA name or format is correct.
make[1]: *** [all] Error 1
make[1]: Leaving directory `/lucida/lucida/tools'
make: *** [local] Error 2

**Comment by yunshengb** [comment]
I assume you are using Ubuntu 14. Can you backup your repository sources list `/etc/apt/sources.list` and compare with this:

```
# deb cdrom:[Ubuntu 14.04.4 LTS _Trusty Tahr_ - Release amd64 (20160217.1)]/ trusty main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted
deb-src http://us.archive.ubuntu.com/ubuntu/ trusty main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted
deb-src http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://us.archive.ubuntu.com/ubuntu/ trusty universe
deb-src http://us.archive.ubuntu.com/ubuntu/ trusty universe
deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates universe
deb-src http://us.archive.ubuntu.com/ubuntu/ trusty-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://us.archive.ubuntu.com/ubuntu/ trusty multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ trusty multiverse
deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ trusty-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://us.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu trusty-security main restricted
deb-src http://security.ubuntu.com/ubuntu trusty-security main restricted
deb http://security.ubuntu.com/ubuntu trusty-security universe
deb-src http://security.ubuntu.com/ubuntu trusty-security universe
deb http://security.ubuntu.com/ubuntu trusty-security multiverse
deb-src http://security.ubuntu.com/ubuntu trusty-security multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu trusty partner
# deb-src http://archive.canonical.com/ubuntu trusty partner

## This software is not part of Ubuntu, but is offered by third-party
## developers who want to ship their latest software.
deb http://extras.ubuntu.com/ubuntu trusty main
deb-src http://extras.ubuntu.com/ubuntu trusty main
```

**Comment by yunshengb** [comment]
Also, see if [this post](http://askubuntu.com/questions/452595/cannot-add-ppa-behind-proxy-ubuntu-14-04) and [this post](http://askubuntu.com/questions/429803/cannot-add-ppa-please-check-that-the-ppa-name-or-format-is-correct) help.

**Comment by yunshengb** [comment]
Third, [the script described here](http://askubuntu.com/questions/65911/how-can-i-fix-a-404-error-when-using-a-ppa-or-updating-my-package-lists) automatically removes offending software-sources and solved the issue on my computer.

**Comment by prakharnigam** [comment]
Thanks for quick reply. :+1: 
That issue is resolved by above details. But now i am facing following issue

**Comment by prakharnigam** [comment]
./gradlew build
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:startScripts UP-TO-DATE
:distTar UP-TO-DATE
:distZip UP-TO-DATE
:assemble UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build UP-TO-DATE

BUILD SUCCESSFUL

Total time: 14.855 secs

This build could be faster, please consider using the Gradle Daemon: http://gradle.org/docs/2.4/userguide/gradle_daemon.html
make[2]: Leaving directory `/Hobby/lucida/lucida/lucida/calendar'
make[2]: Entering directory `/Hobby/lucida/lucida/lucida/speechrecognition'
make -C kaldi_gstreamer_asr all || exit 1;
make[3]: Entering directory `Hobby/lucida/lucida/lucida/speechrecognition/kaldi_gstreamer_asr'
make[3]: Leaving directory `/Hobby/lucida/lucida/lucida/speechrecognition/kaldi_gstreamer_asr'
make[2]: Leaving directory `/Hobby/lucida/lucida/lucida/speechrecognition'
make[2]: Entering directory `/Hobby/lucida/lucida/lucida/djinntonic'
cd tools; \
	./install-protobuf.sh; \
	./install-caffe.sh; \
	cd ..; \
	python -mthrift_compiler.main --gen cpp2 ../lucidaservice.thrift; \
	python -mthrift_compiler.main --gen cpp2 ../lucidatypes.thrift; \
	cd models; \
	fname=djinn-weights-1.0.tar.gz; \
	wget http://web.eecs.umich.edu/~jahausw/download/name; \
	tar xvzf name; \
	rm -rf name; \
	cd ../imc; \
	make; \
	cd ../dig; \
	make; \
	cd ../face; \
	make
Protobuf already installed, skipping
Caffe already installed, skipping
--2016-07-25 20:24:10--  http://web.eecs.umich.edu/~jahausw/download/name
Resolving web.eecs.umich.edu (web.eecs.umich.edu)... 141.212.113.110
Connecting to web.eecs.umich.edu (web.eecs.umich.edu)|141.212.113.110|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-07-25 20:24:11 ERROR 404: Not Found.

tar (child): name: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
make[3]: Entering directory `/Hobby/lucida/lucida/lucida/djinntonic/imc'
g++ -Wall -I/usr/local/include -I/usr/include/atlas -std=c++11 -O3  -I../tools/caffe/distribute/include/ -DCPU_ONLY -std=c++11 -c IMCHandler.cpp -o IMCHandler.o
In file included from ../tools/caffe/distribute/include/caffe/blob.hpp:4:0,
                 from ../tools/caffe/distribute/include/caffe/caffe.hpp:7,
                 from IMCHandler.h:6,
                 from IMCHandler.cpp:1:
../tools/caffe/distribute/include/caffe/common.hpp:26:26: error: declaration of namespace ‘gflags’ conflicts with
 namespace gflags = google;
                          ^
In file included from /usr/local/include/folly/ThreadLocal.h:40:0,
                 from /usr/local/include/folly/io/async/EventBaseManager.h:19,
                 from /usr/local/include/thrift/lib/cpp/server/TConnectionContext.h:23,
                 from /usr/local/include/thrift/lib/cpp/EventHandlerBase.h:25,
                 from /usr/local/include/thrift/lib/cpp/TProcessor.h:25,
                 from /usr/local/include/thrift/lib/cpp2/async/AsyncProcessor.h:20,
                 from /usr/local/include/thrift/lib/cpp2/ServiceIncludes.h:5,
                 from ../gen-cpp2/LucidaService.h:9,
                 from IMCHandler.h:4,
                 from IMCHandler.cpp:1:
/usr/local/include/folly/Portability.h:333:18: error: previous declaration of namespace ‘gflags’ here
 namespace gflags {
                  ^
make[3]: *** [IMCHandler.o] Error 1
make[3]: Leaving directory `/Hobby/lucida/lucida/lucida/djinntonic/imc'
make[3]: Entering directory `/Hobby/lucida/lucida/lucida/djinntonic/dig'
g++ -Wall -I/usr/local/include -I/usr/include/atlas -std=c++11 -O3  -I../tools/caffe/distribute/include/ -DCPU_ONLY -std=c++11 -c DIGHandler.cpp -o DIGHandler.o
In file included from ../tools/caffe/distribute/include/caffe/blob.hpp:4:0,
                 from ../tools/caffe/distribute/include/caffe/caffe.hpp:7,
                 from DIGHandler.h:6,
                 from DIGHandler.cpp:1:
../tools/caffe/distribute/include/caffe/common.hpp:26:26: error: declaration of namespace ‘gflags’ conflicts with
 namespace gflags = google;
                          ^
In file included from /usr/local/include/folly/ThreadLocal.h:40:0,
                 from /usr/local/include/folly/io/async/EventBaseManager.h:19,
                 from /usr/local/include/thrift/lib/cpp/server/TConnectionContext.h:23,
                 from /usr/local/include/thrift/lib/cpp/EventHandlerBase.h:25,
                 from /usr/local/include/thrift/lib/cpp/TProcessor.h:25,
                 from /usr/local/include/thrift/lib/cpp2/async/AsyncProcessor.h:20,
                 from /usr/local/include/thrift/lib/cpp2/ServiceIncludes.h:5,
                 from ../gen-cpp2/LucidaService.h:9,
                 from DIGHandler.h:4,
                 from DIGHandler.cpp:1:
/usr/local/include/folly/Portability.h:333:18: error: previous declaration of namespace ‘gflags’ here
 namespace gflags {
                  ^
make[3]: *** [DIGHandler.o] Error 1
make[3]: Leaving directory `/Hobby/lucida/lucida/lucida/djinntonic/dig'
make[3]: Entering directory `/Hobby/lucida/lucida/lucida/djinntonic/face'
g++ -Wall -I/usr/local/include -I/usr/include/atlas -std=c++11 -O3  -I../tools/caffe/distribute/include/ -DCPU_ONLY -std=c++11 -c FACEHandler.cpp -o FACEHandler.o
In file included from ../tools/caffe/distribute/include/caffe/blob.hpp:4:0,
                 from ../tools/caffe/distribute/include/caffe/caffe.hpp:7,
                 from FACEHandler.h:5,
                 from FACEHandler.cpp:1:
../tools/caffe/distribute/include/caffe/common.hpp:26:26: error: declaration of namespace ‘gflags’ conflicts with
 namespace gflags = google;
                          ^
In file included from /usr/local/include/folly/ThreadLocal.h:40:0,
                 from /usr/local/include/folly/io/async/EventBaseManager.h:19,
                 from /usr/local/include/thrift/lib/cpp/server/TConnectionContext.h:23,
                 from /usr/local/include/thrift/lib/cpp/EventHandlerBase.h:25,
                 from /usr/local/include/thrift/lib/cpp/TProcessor.h:25,
                 from /usr/local/include/thrift/lib/cpp2/async/AsyncProcessor.h:20,
                 from /usr/local/include/thrift/lib/cpp2/ServiceIncludes.h:5,
                 from ../gen-cpp2/LucidaService.h:9,
                 from FACEHandler.h:3,
                 from FACEHandler.cpp:1:
/usr/local/include/folly/Portability.h:333:18: error: previous declaration of namespace ‘gflags’ here
 namespace gflags {
                  ^
make[3]: *** [FACEHandler.o] Error 1
make[3]: Leaving directory `/Hobby/lucida/lucida/lucida/djinntonic/face'
make[2]: *** [all] Error 2
make[2]: Leaving directory /Hobby/lucida/lucida/lucida/djinntonic'
make[1]: *** [all-sub] Error 1
make[1]: Leaving directory `Hobby/lucida/lucida/lucida'
make: *** [local] Error 2

**Comment by yunshengb** [comment]
Just fixed. Please `git pull origin master` and `make` again in `lucida/djinntonic`. Thanks!

**Comment by prakharnigam** [comment]
Resolved. Thanks
