### ISSUE TITLE
logic error in install_opencv.sh

### ISSUE THREAD

**Issue by martinmmmeier** [claritylab/lucida#124]
Hi,

i just cloned repo and tried to build master on xubuntu 14.04.5 x64 (fresh install).
make local aborts at install_opencv.sh with message that opencv2/core/core.hpp is not found, but contradictingly stating that opencv is already installed.
Reason is logical error in line 12 of install_opencv.sh, which should be ...
if !installCheck

Can anybody please update this one ?
Thanks!
-Martin

**Comment by yunshengb** [comment]
Fixed. Thank you!
