### ISSUE TITLE
Error when run file /start-asr-server.sh in Sirius

### ISSUE THREAD

**Issue by Hangphuong** [claritylab/lucida#125]
When I run file /start-asr-server.sh in Sirius, I got some errors. I don't know what is it and how to fix it. please give me some comment if you know

WARNING (online2-wav-nnet2-latgen-faster:HasKeyInternal():util/kaldi-table-inl.h:1635) Error opening stream null
ERROR (online2-wav-nnet2-latgen-faster:Value():util/kaldi-table-inl.h:1576) Could not get item for key utterance-id1, rspecifier is scp:echo utterance-id1 null|[to ignore this, add the p, (permissive) option to the rspecifier.
ERROR (online2-wav-nnet2-latgen-faster:Value():util/kaldi-table-inl.h:1576) Could not get item for key utterance-id1, rspecifier is scp:echo utterance-id1 null|[to ignore this, add the p, (permissive) option to the rspecifier.

[stack trace: ]
kaldi::KaldiGetStackTrace()
kaldi::KaldiErrorMessage::~KaldiErrorMessage()
kaldi::RandomAccessTableReaderScriptImplkaldi::WaveHolder::Value(std::string const&)
kaldi::RandomAccessTableReaderkaldi::WaveHolder::Value(std::string const&)
/home/mica/MyKaldi/kaldi-trunk/src/online2bin/online2-wav-nnet2-latgen-faster(main+0x907) [0x7bf08c]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7faca13d5ec5]
/home/mica/MyKaldi/kaldi-trunk/src/online2bin/online2-wav-nnet2-latgen-faster() [0x7be179]

**Comment by yunshengb** [comment]
Are you using the latest version? I cannot find `start-asr-server.sh` in this repo. Please pull the latest change and compile dependencies in `tools` and then kaldi in `lucida/speechrecognition/kaldi_gstreamer_asr`. Thanks!

**Comment by Hangphuong** [comment]
Thank you about your repply.
I download the Sirius verson 1.0.1 on this page:
http://sirius.clarity-lab.org/downloads/#sirius
This is start-asr-server.sh and i done all of steps following this page:
http://sirius.clarity-lab.org/sirius/



2016-08-31 21:03 GMT+07:00 yunshengb <notifications@github.com>:

**Comment by yunshengb** [comment]
Hello,

**Comment by yunshengb** [comment]
I am contacting the original author of Sirius and I will keep you updated. Thanks!

**Comment by Hangphuong** [comment]
Wow, thank you so much. It is great. 
I really want to solve about this error. 
I will try using the lastest ASR .
Thanks again.

**Comment by saijel** [comment]
@Hangphuong if you are still seeing this issue please open a new issue. Thanks!
