### ISSUE TITLE
Minimum requirement of CPU & memory

### ISSUE THREAD

**Issue by AsoulYang** [claritylab/lucida#127]
Hi, I'm new to Lucida,
I just installed the Lucida on an AWS t2.micro machine,
and it was blocked for a long time, (I cannot check other commands because out of memory)
Finally I got

```
virtual memory exhausted: Cannot allocate memory

error: Command "c++ -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -D__STDC_FORMAT_MACROS=1 -Iscipy/sparse/sparsetools -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c scipy/sparse/sparsetools/bsr.cxx -o build/temp.linux-x86_64-2.7/scipy/sparse/sparsetools/bsr.o" failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-PWPkd3/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-EOtGWV-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-PWPkd3/scipy
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip2')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 28: ordinal not in range(128)
Makefile:4: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/admin/lucida/tools'
Makefile:18: recipe for target 'local' failed
make: *** [local] Error 2
```

Seems the memory is not enough.

Is there a minimum requirement for Lucida? or what's the AWS machine should I choose for Lucida?
Thanks

**Comment by AsoulYang** [comment]
Is Lucida need more CPU or RAM?
I found the minimum requirement for Kubernetes deploy version, the minimum RAM is 16G and Disk is 18G.
If I want to run lucida fluently, should I choose c3.4xlarge, m3.2xlarge, r3.2xlarge or others?
Thanks

**Comment by yunshengb** [comment]
Hi,

The minimum RAM requirement has been updated [here](https://github.com/claritylab/lucida/blob/master/tools/deploy/README.md). It should be 7 GB, NOT 16 GB. Thanks a lot!

**Comment by yunshengb** [comment]
If you want to run Lucida fluently, please provide as much memory and disk space as possible, and also be aware that the actual performance can be affected by other factors like

**Comment by yunshengb** [comment]
Let me know if this helps and if you have further questions. Thanks!

**Comment by saijel** [comment]
Hi @AsoulYang, please open a new issue if still have questions about the minimum requirements. Thanks!
