### ISSUE TITLE
IPA image VM connection refused: localhost:8089/demos 

### ISSUE THREAD

**Issue by KrishnaPG** [claritylab/lucida#130]
Trying the "Build your own IPA image" VM shared in the tutorial http://lucida.ai/tutorial.html

The tutorial notes indicate to run `docker-compose up` and then `localhost:8081` 

The `localhost:8081` worked fine. When clicked on submit button, though, it went to `localhost:8080/demos` and 'connection refused'. 

How to troubleshoot this?

**Comment by yunshengb** [comment]
The tutorial and the image in the website has not been updated yet. The ones in this Github repo are the latest. They are similar but the latest version has more features and functionalities, and I can help you quicker if you use that. 

However, I can contact the author for you if you prefer to use that version. Please tell me your choice. Thanks a lot!

**Comment by KrishnaPG** [comment]
Thank you @yunshengb The reason for using that tutorial VM was it looked like easy to setup with single step (just download and launch the VM).

Setting it from this repo, looks like a much involved process and also the 16GB RAM requirement was little bit on the high side (given that the VM from tutorial was using around just 6GB RAM).

Will try to give this repo a try. Wish the RAM requirements could be brought down, though.

**Comment by yunshengb** [comment]
Hi,

If you disable certain services, the memory usage will be brought down. For example, you can modify [this line](https://github.com/claritylab/lucida/blob/master/tools/deploy/start_services.sh#L35) so that you only start the services you need.

**Comment by yunshengb** [comment]
Just deployed all the services using Kubernetes on my virtual machine:

![image](https://cloud.githubusercontent.com/assets/8391016/18806340/d7fcb3d4-81f7-11e6-9245-8e58813e6c7e.png)

I have corrected the [README](https://github.com/claritylab/lucida/blob/master/tools/deploy/README.md).

Please tell me if you have further concerns. Thanks!

**Comment by KrishnaPG** [comment]
Thanks @yunshengb That is much better now. Will check it.
