### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by k0105** [claritylab/lucida#170]
Hi,

now that two people are working on Lucida again and since you offered it: Could you provide a brief roadmap of what changes you are working on / which aspects have already changed?

Thank you in advance.

Best wishes,
k0105

**Comment by saijel** [comment]
I just created a [Roadmap wiki](https://github.com/claritylab/lucida/wiki/Roadmap). Right now the tasks are pretty specific and the first 5 tasks have PRs out.

**Comment by k0105** [comment]
Thank you - that's very helpful.
