### ISSUE TITLE
Innstalation and first run -  pocketsphinx empty string

### ISSUE THREAD

**Issue by Timopheym** [claritylab/lucida#21]
Firstly, thank you very much for so interesting approach! 
When i run  `pocketsphinx_continuous -infile where.is.las.vegas.wav`
I got a lot of information plus `... there is las vegas ...` so it seems to work.

But! When I run `./start-asr-server.sh pocketsphinx` and  parallel 
Starting server on localhost:8081, use <Ctrl-C> to stop

```
$ ./sirius-asr-test.sh ../inputs/questions/where.is.las.vegas.wav
Your audio file is:
../inputs/questions/where.is.las.vegas.wav
Sending request to server...

***********************************************
```

and the server writes `transcript []:` (empty) 
So, the question - why?

I am using last version 8b71aba386024fa5783e1e677d909333bd43dd57 for now.

Also I can't compile kaldi: 

``````
$ sudo ./compile-sirius-servers.sh
[sudo] password for timopheym:
Sphinx4 server done.
Java Pocketsphinx server done.
libtool: install: warning: relinking `libsphinxad.la'
libtool: install: warning: relinking `_sphinxbase.la'
libtool: install: warning: relinking `libpocketsphinx.la'
libtool: install: warning: relinking `_pocketsphinx.la'
C++ Pocketsphinx server done.
***configure failed: Could not find file /include/fst/fst.h:
    you may not have installed OpenFst.  See ../tools/INSTALL *** ```

So, installation process is not simple... ;) (it took me about 2 hours), but I hope we will go through it..

``````

**Comment by Timopheym** [comment]
I installed kaldi by myself from official instruction. 
```
svn co svn://svn.code.sf.net/p/kaldi/code/trunk kaldi-trunk
cd kaldi-trunk/tools/; make; cd ../src; ./configure; make
```
I also needed this fix for ATLAS installation: 
```sudo apt-get install gfortran f2c libcnf-dev ```
(from http://askubuntu.com/questions/472146/building-atlas-and-later-octave-w-atlas)

Also i was need to install sox...

But after i did run kaldi ast server and asked for a speed of light, i've got in a loop. Can we catch and debug this?

```
Exception happened during processing of request from ('127.0.0.1', 45591)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./start-asr-dnn-server.py", line 59, in do_POST
    res = shcin(filename, server_process)
  File "./start-asr-dnn-server.py", line 26, in shcin
    server.stdin.write(stdin_data)
IOError: [Errno 32] Broken pipe
``` 
Ubuntu 14.04 x64.

**Comment by Timopheym** [comment]
Eh, sorry, write a lot... but is it possable to get ```wiki_indri_index.tar.gz``` withot downloading 11 gig's, 'cose i wanna contribute (if i will run the whole system one time... =))

**Comment by jhauswald** [comment]
Hi Timopheym,

Thanks for your interest and detailed write up of your experience so far! I apologize for the delay, we are currently all at a conference presenting this work and we have limited time. Once we're back, we'll be more readily available.

To address some of your issues:

11GB tar: the services are decoupled, so as you noticed you can still run the image and voice systems to test their implementation. The question-answer service needs the 11GB wikipedia index to give answers so you'll need it if you want to play around with that!

Image matching: what version of boost and protobuf do you currently have installed?

Kaldi: so it seems you got Kaldi set up but there's an issue with the python server? This is the output from running `./start-asr-server.sh` and in another terminal sending wav files right?

Keep updating me on your progress and I'll try to answer as frequently as possible, time permitting. Thanks!

**Comment by Timopheym** [comment]
Hey, thanks for so warm response. Yes, I run ./start-asr-server.sh and in
another terminal was sending wav files. Now I am downloading 11 tar and
will try to run it on my MacBook.
I didn't install  boost and protobuf, so I hoped that prepared scripts
would do that..

For Kaldi, I think that service for some reason was stoped (without any
logs) and the python script could not find it. Anyway, i will try to setup
it one more time... but I hope that in the future there will be and easier
way to do it (without running 3 scripts with sudo ;) ) may be some ant
script?

Good luck with your conference, the opensource AI solution will change a
lot I guess =)

On Sat, Mar 14, 2015 at 6:23 PM, Johann Hauswald <notifications@github.com>
wrote:

> Hi Timopheym,
>
> Thanks for your interest and detailed write up of your experience so far!
> I apologize for the delay, we are currently all at a conference presenting
> this work and we have limited time. Once we're back, we'll be more readily
> available.
>
> To address some of your issues:
>
> 11GB tar: the services are decoupled, so as you noticed you can still run
> the image and voice systems to test their implementation. The
> question-answer service needs the 11GB wikipedia index to give answers so
> you'll need it if you want to play around with that!
>
> Image matching: what version of boost and protobuf do you currently have
> installed?
>
> Kaldi: so it seems you got Kaldi set up but there's an issue with the
> python server? This is the output from running ./start-asr-server.sh and
> in another terminal sending wav files right?
>
> Keep updating me on your progress and I'll try to answer as frequently as
> possible, time permitting. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhauswald/sirius/issues/21#issuecomment-80531437>.
>



-- 
Kind regards,
Timophey Molchanov.

First do it, then do it right, then do it fast.

**Comment by Alphin** [comment]
the reason is because the socialist illuation of a coomon nation causes us to behave seperate

**Comment by Alphin** [comment]
sorry i i just pasted the document into the wrong comment box,, u see i am also i a history group

**Comment by sedrubal** [comment]
May you please provide the `wiki_indri_index.tar.gz` as a separated download? I have problems to extract the nested archieve out of the other archeives. And please provide checksums for the downloads on the homepage. It seems like my download is broken...

Thank you :)

**Comment by Alphin** [comment]
okk

**Comment by Meesingo** [comment]
I'm also receiving this error in `./start-asr-server.sh` when I test it with `./sirius-asr-test.sh ../inputs/questions/what.is.the.speed.of.light.wav`:

    ----------------------------------------
    Exception happened during processing of request from ('127.0.0.1', 54429)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
        self.finish_request(request, client_address)
      File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
        self.handle()
      File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
        self.handle_one_request()
      File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
        method()
      File "./start-asr-dnn-server.py", line 59, in do_POST
        res = shcin(filename, server_process)
      File "./start-asr-dnn-server.py", line 26, in shcin
        server.stdin.write(stdin_data)
    IOError: [Errno 32] Broken pipe
    ----------------------------------------
`

**Comment by saijel** [comment]
Hi @Timopheym, please open a new issue if this problem still persists. Thanks!
