### ISSUE TITLE
unable to find wiki_indri_index_.tar.gz

### ISSUE THREAD

**Issue by androidSmart** [claritylab/lucida#219]
I can't find the wiki knowledge base using the provided link, it's down or removed, if anyone has a link to the file, I would appreciate..

**Comment by KamalGalrani** [comment]
Go to tools folder and download using the download_wiki... script.

Kamal

**Comment by androidSmart** [comment]
Thank you for your replay Kamal, but it is the original link of the file(http://web.eecs.umich.edu/~jahausw/download/wiki_indri_index.tar.gz) not working.., if you know other alternative or if you have the file somewhere please let me know...

**Comment by SeansRightHere** [comment]
I have it downloaded.  How to host is a problem.  Suggestion?

**Comment by androidSmart** [comment]
@SeansRightHere here is my email address(ashenafi1127@gmail.com) , you can send it using , https://www.myairbridge.com/eng/ , 
Thank you..

**Comment by jhauswald** [comment]
Hey everyone sorry about that, can you try again? Got it all fixed up :)

**Comment by SeansRightHere** [comment]
Great, saves me an 11gb upload.
Thanks, Johann.

**Comment by Azuresonance** [comment]
> Hey everyone sorry about that, can you try again? Got it all fixed up :)

@jhauswald 
Do you mind fixing that link again? Also, the entire sirius.clarity-lab.org seem to be down.
Thank you.

**Comment by jhauswald** [comment]
Hey @Azuresonance ! Yes apologies, I don't have access to that account for hosting anymore. While I figure out a better way to host the index, you can download it from this [Drive Link](https://drive.google.com/file/d/16QTGBVpInG1gMn4dtg0a53vH2TkVbNGQ/view?usp=sharing). 

You can also use [GDown](https://github.com/wkentaro/gdown) to download it programmatically. I'm still investigating if I update the script to link to GDrive or if I can find a simpler place to host. Hope that fixes your issue in the short-term :)

**Comment by Azuresonance** [comment]
@jhauswald 
It works! Thank you very much for your help.
