### ISSUE TITLE
Issue With Install on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by EmpireofKings** [claritylab/lucida#226]
Hello World, so far the install using "make local" is working just fine until i reach the fbthrift script.

Any advice would be of much help

``+ make
make  all-recursive
make[1]: Entering directory '/media/nvidia/Astro/lucida/tools/fbthrift/thrift/build/deps/folly/folly'
Making all in .
make[2]: Entering directory '/media/nvidia/Astro/lucida/tools/fbthrift/thrift/build/deps/folly/folly'
/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -msse4.2 -std=gnu++1y -g -O2 -MT detail/libfollybasesse42_la-RangeSse42.lo -MD -MP -MF detail/.deps/libfollybasesse42_la-RangeSse42.Tpo -c -o detail/libfollybasesse42_la-RangeSse42.lo `test -f 'detail/RangeSse42.cpp' || echo './'`detail/RangeSse42.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -msse4.2 -std=gnu++1y -g -O2 -MT detail/libfollybasesse42_la-RangeSse42.lo -MD -MP -MF detail/.deps/libfollybasesse42_la-RangeSse42.Tpo -c detail/RangeSse42.cpp  -fPIC -DPIC -o detail/.libs/libfollybasesse42_la-RangeSse42.o
g++: error: unrecognized command line option ‘-msse4.2’
Makefile:1714: recipe for target 'detail/libfollybasesse42_la-RangeSse42.lo' failed
make[2]: *** [detail/libfollybasesse42_la-RangeSse42.lo] Error 1
make[2]: Leaving directory '/media/nvidia/Astro/lucida/tools/fbthrift/thrift/build/deps/folly/folly'
Makefile:1798: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/media/nvidia/Astro/lucida/tools/fbthrift/thrift/build/deps/folly/folly'
Makefile:1089: recipe for target 'all' failed
make: *** [all] Error 2
Failed to install Facebook Thrift
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1
``

**Comment by EmpireofKings** [comment]
To further clarify i am running on ubuntu 16.04LTS

**Comment by samiurkh1n** [comment]
The issue is tied to the "-msse4.2" option not being recognized. This is likely because your architecture [doesn't support](https://en.wikipedia.org/wiki/SSE4) the SSE4.2 instruction set.

You could try replacing that flag with `-march=native` to allow g++ to make that decision on what architecture flags are appropriate. You should also report this issue to [fbthrift](https://github.com/facebook/fbthrift/issues), as this isn't an issue with lucida.
