### ISSUE TITLE
Lucida on Raspberrry Pi Kubernetes Cluster

### ISSUE THREAD

**Issue by mrinformatics** [claritylab/lucida#227]
Is it possible to run Lucida Project on Raspberry Pi 3 Kubernetes Cluster with 20 Nodes? As per the documentation, the device needs to have 7GB of memory. If ignored, will it run on RPi K8 Server?

**Comment by JeremyARussell** [comment]
I see you've already closed the issue, but just to provide an answer, certain packages that make up the Lucida project will not run if they don't have enough memory to run off of. For example the QA service (if my memory serves, I ran into this last month) won't even compile on systems without enough RAM. I was running a 4 gig setup and had to upgrade before I was able to get the package to compile.
