### ISSUE TITLE
ffmpeg requires PPA on Ubuntu

### ISSUE THREAD

**Issue by gitfoxi** [claritylab/lucida#23]
`get-dependencies.sh` seems to think Ubuntu provides `ffmpeg`. They don't. You can work around this using a PPA as described:-

http://www.noobslab.com/2014/12/ffmpeg-returns-to-ubuntu-1410.html

**Comment by d4ndo** [comment]
It seems that you don't need libffmpeg at all. I just compiled opencv without ffmpeg and match does not need any ffmpeg feature.

cmake -DWITH_FFMPEG=OFF

**Comment by d4ndo** [comment]
Oh. Sorry. You are talking about ffmpeg not libffmpeg to compile match. Misunderstood that.

**Comment by yunshengb** [comment]
Please pull the latest change and see if the problem still exists. Thanks!

**Comment by saijel** [comment]
Hi @gitfoxi, please open a new issue if this problem still persists. Thanks!
