### ISSUE TITLE
Lucida on ArchLinux?

### ISSUE THREAD

**Issue by Eragonfr** [claritylab/lucida#230]
I want to compile Lucida on my computer, but I'm with ArchLinux.
How can I install dependencies and run scripts ?

**Comment by cassiosantos** [comment]
Hi @Eragonfr !

For a easy way to try Lucida, please see: https://github.com/k0105/mini-lucida

**Comment by Eragonfr** [comment]
`This is a minimal repository containing everything to setup Lucida via Kubernetes on an Ubuntu host. `
I am on ArchLinux, apt does not exist. The package manager is pacman.

**Comment by nils-van-zuijlen** [comment]
You should make lucida installable without the use of apt or dpkg, because not everyone is on a Debian(-like) distribution of Linux.

**Comment by nils-van-zuijlen** [comment]
Then, you may create a package adapted to Debian. And @EragonFr may create an AUR package for Archlinux.
