### ISSUE TITLE
Using Lucida from Ubuntu terminal

### ISSUE THREAD

**Issue by tabz11** [claritylab/lucida#231]
Hi,  I have installed Lucida on ubuntu 16.04 terminal, using `sensible-browser` command to view the webpage, I can register successfully but when try to log in I get an error `method not allowed for requested URL`?

**Comment by JeremyARussell** [comment]
Have you had any progress figuring this out?

Can you copy the output of the Command Center? It should have some details on what's going on when you attempt to login.
