### ISSUE TITLE
Lucida Project Status?

### ISSUE THREAD

**Issue by JeremyARussell** [claritylab/lucida#232]
Good morning everyone,

I have been working on updating Lucida to catch it up with the latest versions of Ubuntu as well as the latest versions of constituent packages, etc. My aim is to really turn Lucida into a much smoother experience to compile and get set up. I would love to be able to do it along side anyone from ClarityLabs or Clinc (not sure who technically "owns" Lucida in that regards) but I don't see any activity in the repo and I haven't received any responses to my inquiries so far that would indicate people are already working on the project.

So my question is this, is anyone officially working on it? If not would we be able to get something arranged so that development can continue in an official capacity? Or will we as the open source community just need to accept that it's dead at this point and form and start fresh? (relatively speaking)

Any and all feedback from anyone in charge would be awesome, in particular I'm looking at Johann and Jason :p but if anyone else has the official answers I'd be glad to hear them.

**Comment by mnba** [comment]
They created some commercial entity and seems that entity sold some hot buzzwords to some venture capitalist(s), this would explain why they long time do not show any work on public. Youtube contains their presentation of how cool is their technology.

**Comment by SeansRightHere** [comment]
Finie, sold to USAA bank and insurance. Huge price tag. Nobody is worrying about student debt.

Thanks,

Sean Hamilton 
Seansrighthere@gmail.com
210-464-1718

**Comment by JeremyARussell** [comment]
I've tried reaching out to them through their website and through the old Slack group but nothing so far. I'm going to try submitting a pull request just to see if that is set to notify anyone. If you're interested in checking out any of the changes I've been working on my repo is open to everyone and has quite a few random bug fixes, etc. I had hoped to just help jump start development on Lucida again but looks like I'll have to go the way of the fork.

On another note I'm starting up another project that I'm using what I've learned from Lucida and a few other open source online AI Virtual Assistants, I've already bought the website and started on a roadmap that should be posted sometime next month. So stay tuned for that if you're interested in a virtual assistant that is easily install-able and customizable.

**Comment by consiliera** [comment]
Hi all, they seem to have taken everything to set up "Clinc AI", selling their "sophisticated AI Training Platform" for 995 US$/month. Hauswald is a co-founder. I just stumbled upon this because I've just updated my mindmap of tools & resources for AI & bot creation (with a focus on open source) and now just removed Clinc from the map. You can see it here (public): https://mm.tt/1197046494?t=JdSqbd80nB

**Comment by dmichelin** [comment]
I'm not in charge or anything but I'm an employee at Clinc. There hasn't been any talk of handing the repo over to the community but I'll bring it up with the company. FWIW Our stack now is very different compared to the repo here. Hope this is helpful.

**Comment by JeremyARussell** [comment]
@dmichelin Oh hey thanks that would probably be super useful for all of us here to know so we can best decide how to use our time going forward. Appreciate the assist, can't wait to hear back anything official :smiley:

**Comment by JeremyARussell** [comment]
Hi @dmichelin 
Were you able to speak to Jason, Johann or another person who can let us know what's going on with Lucida?

**Comment by dmichelin** [comment]
Yup! Sorry about the late response. I'll be taking over maintaining the project, so officially as of now the development of this could be considered `active`. I saw that @JeremyARussell has been working on an upstream branch, so I'd love to chat and get some context on what you've been working on to get them downstream.

**Comment by JeremyARussell** [comment]
@dmichelin You've actually caught me while I was online and working on my command center windows / visual studio port :D

I've got my own slack workspace that I'll be using for the AI work I'm doing [here](https://civa-project.slack.com/) but I still have my Lucida slack account logged in if that one works for you. (Which actually reminds me, Johann and myself are admins so if he hasn't hooked you up yet on that slack workspace I can get you set up)

You should be able to find me in both places for most of the day, though I can and will suddenly drop out randomly due to being a father of 3 :p 

Oh and I will go ahead and close this issue since the project is officially active again :)

**Comment by dmichelin** [comment]
Funnily enough I'm not set up on that slack. You can invite me with my personal email daniel.c.michelin@gmail.com.
