### ISSUE TITLE
Create a Vagrantfile to automate the process of creating a development environment

### ISSUE THREAD

**Issue by tomzx** [claritylab/lucida#26]
Since the process of getting started is quite lengthy, I would suggest that a Vagrantfile be setup with the necessary configuration to make it a one command install (basically `vagrant up`).

This will provide a replicable development environment for developers that may be interested in contributing to sirius.

**Comment by hansgru** [comment]
+1

**Comment by DanielHeath** [comment]
How well supported if windows/BSD/etc? If not very, Docker/other container-based runtime is probably the way to go - same one-command setup `docker run` with a far lower RAM overhead.

**Comment by debanjum** [comment]
Vagrant is available on Windows, Mac, Linux. Docker uses linux containers and hence is a little more tied to the specific kernel

**Comment by DanielHeath** [comment]
`boottodocker` works pretty well to alleviate that (a vagrant image with a minimal docker config). 
I've spent a lot of time with both (although it's been ~2 years since I used vagrant) building replicable development environments. 

From an end-user perspective, docker is slightly less ram-hungry on linux and about as ram-hungry everywhere else.
From a maintainers perspective, docker is slightly more complex if you support it via boot2docker.
From the perspective of the person setting up a replicable development environment, docker is a *vast* improvement, because you can test a small change to the setup script in ~2-3 seconds (when I used vagrant this was more like 2-3 minutes for a small project and 2-3 hours for a large one).

**Comment by viklas** [comment]
+1 I'd be happy to help with this work. I just came across Sirius today and putting together a dockerfile is the obvious starting point (can't wait to see it in action). Or if anyone has already had break-throughs on the docker side, I'd be happy to help with any other 'infradev' tasks. I agree with the approach that says let's get it working at the simple 'docker run' level first...vagrant (or any other private/public cloud provider deployment supporting containers) can come second.

**Comment by viklas** [comment]
Quick update - started docker composition process. Large number of dependencies (10+) have been added to the 'get-dependencies.sh' file, and some other items (GCC versions, etc). Biggest issue is we are now over 10GB for the docker image, before compiling the sirius server binaries. 10Gb is the default upper limit for an image using devicemapper (can be modified, but that would make the image undeployable elsewhere). So the revised approach is to look to break each server component into its own docker image (more aligned to the micro-services model and hopefully much smaller per component). If anyone is having success using a different approach, please shout out.

**Comment by DanielHeath** [comment]
10 GB sounds pretty crazy. Where is the space going?

**Comment by viklas** [comment]
Here's the 'docker history' on the current image. This tallies 7GB, but there are more dependencies, etc pulled down during 'compile binaries'...which is what I was running manually when I hit the 10GB limit. So assume at least another 3GB on top of the layers below.

..a few changes in train which will shrink the footprint to something more manageable...
- Revert to base java image, over ubuntu (leaner)
- Split the application up into '1 process per container'
- Build v Run images...hopefully there's some bloat to remove from the 'build' image

Got any ideas how to streamline further?

IMAGE               CREATED             CREATED BY                                      SIZE
a4cac1169cef        18 hours ago        /bin/sh -c #(nop) ENTRYPOINT [bash]             0 B
6273bf6c9b5b        18 hours ago        /bin/sh -c ./get-kaldi.sh                       2.113 GB
4af7d4a54205        18 hours ago        /bin/sh -c ./get-opencv.sh                      3.49 GB
cf54c9f0b607        18 hours ago        /bin/sh -c ./get-dependencies.sh                931.3 MB
2126c5f5cdd3        18 hours ago        /bin/sh -c echo 'deb http://us.archive.ubuntu   1.958 kB
a247e944152c        18 hours ago        /bin/sh -c #(nop) WORKDIR /opt/sirius/sirius-   0 B
2016aed38612        18 hours ago        /bin/sh -c #(nop) ADD dir:080e01bded1aaf80d1a   328.6 MB
2d460516e1bd        18 hours ago        /bin/sh -c mkdir /opt/sirius && mkdir /opt/si   0 B
2103b00b3fdf        9 days ago          /bin/sh -c #(nop) CMD [/bin/bash]               0 B
4faa69f72743        9 days ago          /bin/sh -c sed -i 's/^#\s*\(deb.*universe\)$/   1.895 kB
76b658ecb564        9 days ago          /bin/sh -c echo '#!/bin/sh' > /usr/sbin/polic   194.5 kB
f0dde87450ec        9 days ago          /bin/sh -c #(nop) ADD file:a2d97c73fb08b9738c   188.1 MB

**Comment by DanielHeath** [comment]
I'd expect the run image to be *way* smaller than the build image.

**Comment by DanielHeath** [comment]
What about 1 container per build?

**Comment by viklas** [comment]
Yep - that's where it's heading...a run container with all the binaries, but the ability to 'docker run' with either a server process per container, or the full suite (web front end can go in it's own container). And yep, splitting out the build containers is the first step...thinking we start with a base image we re-use everywhere (java + sirius git clone), then split out different build images for pulling specific dependencies and compiling discrete components, then lastly, a run-time image to pull it back together. Something like that...

**Comment by nileshtrivedi** [comment]
Docker Compose (earlier known as Fig.sh) can be useful for this.

**Comment by viklas** [comment]
Another brief update on the docker preparation. There's now a working dockerfile to build the base image (ubuntu 12.04) with all the dependencies (all the apt-gets from the scripts pulled into here for visibility). The image is pushed to the registry at that point (1GB, takes about 15 mins to docker build).

That's then followed with a docker run command, with the sirius repo mounted as a volume to /opt/sirius, and then get-opencv, get-kaldi and the compilation kicks off via a start.sh script. This is v0.1, the biggest issue being the time it takes to perform the compile, in preparation for running the servers...about 30 mins. Once we've confirmed the build works (will test each of the servers), I'll raise a PR for review. If you're interested, the work in progress is in the emergingstack/sirius fork. Will also need to merge in recent commits, but should be too much of a problem. This approach (mounting repo as a volume) stops us hitting the 10Gb limitation, but will still need to be worked through to fully automate (we use jenkins to get us over that hump).

Also, I put together a dockerfile for sirius-web too, but that's a minor thing compared to the server components...almost there.

**Comment by viklas** [comment]
Pull Request #55 has been raised. Please review and suggest any modifications. 

I'd suggest this particular issue be closed once the tests pass - there's another PR for a 'native' vagrant build, and this covers off the basic docker requirements. We can raise a new issue to track the outstanding server components (IMM & ASR).

**Comment by jhauswald** [comment]
We've been following the docker/vm push closely and this is how it looks from our side:

<img src="http://thumbpress.com/wp-content/uploads/2013/05/I-Have-No-Idea-What-Im-Doing-8.jpg" width="250" height="186" />

I've personally never worked with docker so its a good opportunity for me to learn about it before merging  it in so I appreciate the patience!

**Comment by viklas** [comment]
That dog needs to take some life lessons from this Redditor:
http://www.reddit.com/r/tifu/comments/306xj9/tifu_by_not_wearing_any_clothes/

Must admit, sirius proved to be about 10x harder to nail down into a basic dockerfile than we first thought, but will be worth it (should get some good distributed development going). There's still some techniques to streamline, and most important to that would be trimming down the sirius repo to a much smaller footprint (store any big files externally on s3 or something)...but this approach works for now to get things moving.
