### ISSUE TITLE
remove hardcoded magic number of threads in build scripts

### ISSUE THREAD

**Issue by mseeber** [claritylab/lucida#38]
In some buildscripts, the number of threads for concurrent builds is set to a fixed magical number:

https://github.com/jhauswald/sirius/blob/master/sirius-application/get-opencv.sh
https://github.com/jhauswald/sirius/blob/master/sirius-application/compile-sirius-servers.sh

here it is probably kind of ok, i guess travis does not do concurrent builds:
https://github.com/jhauswald/sirius/blob/master/.travis.yml

I am not sure, that 4 is always for everyone a good choice, as this number is completely system dependent. Usually you would default to non concrrent builds (-j 1) and give the user the option to set the number of threads manually or you could query nproc(1) to find out the number of cores.

**Comment by jhauswald** [comment]
This can now be set in the top level Makefile (https://github.com/claritylab/lucida/blob/master/Makefile#L6) for the build.
