### ISSUE TITLE
Clarify that sirius is beta and insecure

### ISSUE THREAD

**Issue by sedrubal** [claritylab/lucida#40]
I played around with sirius and detected that the `sirius-web` app gives you a python terminal if an error occurres. And I think that the whole project is at this time only for developers and should not be served for the public.

Just my minds ;)

**Comment by irl** [comment]
The bug report here should have been that "the sirius-web app gives you a python terminal if an error occurs" which may break the "no suprises" rule for software security.

The BSD license under which Sirius is distributed contains a disclaimer of liability and it is always essentially up to the end-user to decide whether or not a piece of software is suitable for themselves.

Either the presence of the shell should be documented clearly, or should only be enabled in a debugging mode. A vague "this is beta" helps no one.

**Comment by sedrubal** [comment]
ack

**Comment by yunshengb** [comment]
The front end is updated as in `lucida/lucida/commandcenter`. Please check it again. Thanks.

**Comment by saijel** [comment]
Hi @sedrubal,  please open a new issue if this problem still persists. Thanks!
