### ISSUE TITLE
libsdl1.2-dev will not install on Ubuntu 14.04

### ISSUE THREAD

**Issue by electrickite** [claritylab/lucida#43]
One of the packages installed by `get-opencv.sh` is `libsdl1.2-dev`. This fails to install on a fresh Ubuntu 14.04 Desktop. Errors below:

```
$ sudo apt-get install libsdl1.2-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libcheese-gtk23 : Depends: libclutter-gtk-1.0-0 (>= 0.91.8) but it is not going to be installed
                   Depends: libcogl15 (>= 1.15.8) but it is not going to be installed
 libcheese7 : Depends: libclutter-gst-2.0-0 (>= 0.10.0) but it is not going to be installed
              Depends: gstreamer1.0-clutter but it is not going to be installed
 libclutter-1.0-0 : Depends: libcogl-pango15 (>= 1.15.8) but it is not going to be installed
                    Depends: libcogl15 (>= 1.15.8) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

This error causes the entire command to fail, which will prevent all of those dependencies from being installed.

**Comment by Nalum** [comment]
I am also seeing this. Is there anyway around it?

**Comment by qknight** [comment]
# theory: how to fix this
**warning: by using 'dpkg --purge --force all' you can easily brick your system and i did once for finding out this way of how to successfully install libsdl1.2-dev**

**note:** my blocker list was slightly different but i think that this concept should also apply to electrickite's issue

anyway, i had similar errors with installing libsdl1.2-dev on 14.04 and what i did was basically very similar to what i've documented at [1]. i first followed all the **Depends: libclutter-gtk-1.0-0 (>= 0.91.8) but it is not going to be installed** to find the blockers, then removed them brutally with:

    dpkg --purge --force all libfoo-1.2-bar-ubuntu-0-1

afterwards do;

    apt-get -f install

[1] http://blog.lastlog.de/posts/ubuntu-14.04-apt_problems/

**note:** here **apt-get -f install** reports that it couldn't repair my install! i continued to remove other blockers and tried again with success!

# my command log for installing libsdl1.2-dev
``` 
apt-get install libsdl-1.2-dev
apt-get install libglu-dev
apt-get install libgl1-mesa-dev
dpkg --purge --force all libgl1-mesa-glx
apt-get -f install
apt-get install libgl1-mesa-glx
dpkg -l | grep mesa
dpkg --purge --force all libegl1-mesa
for i in libegl1-mesa-drivers libgl1-mesa-dri libglapi-mesa libgles2-mesa libglu1-mesa libopenvg1-mesa libwayland-egl1-mesa; do dpkg --purge --force all $i; done
apt-get -f install
... here apt-get -f install was so broken it couldn't help me at all ...
aptitude install libsdl1.2-dev
dpkg --purge --force all libsdl1.2debian
apt-get install libsdl1.2debian
apt-get install libsdl1.2-dev
```

**Comment by saijel** [comment]
Hi @electrickite, please open a new issue if this problem still persists. Thanks!
