### ISSUE TITLE
about performace of kaldi

### ISSUE THREAD

**Issue by HarveyLiuFly** [claritylab/lucida#52]
when I test the ASR part of kaldi, with any example wav file, the server should take more than 10 seconds to response the answer. Is the time cost normal for a PC?

**Comment by Compy** [comment]
The part they neglected to mention in their paper is they're using a $20,000+ server to actually do the processing that has about 8 GPUs in it that cost around $3k each.

However, I asked a question on their group about verifying that Kaldi is actually using the GPU since the nvidia monitor doesn't show memory usage on the card changing at all, and nothing.  Sadly, support just isn't there for this project.

**Comment by jhauswald** [comment]
@HarveyLiuFly: this sounds pretty normal (don't know much about your environment though). We were able to speed up Kaldi a lot by linking it to [ATLAS](http://math-atlas.sourceforge.net/) and compiling ATLAS using [AVX](http://en.wikipedia.org/wiki/Advanced_Vector_Extensions) (if you have an x86 based system. Also compile Kaldi using AVX extension. This isn't included yet as it was a hacked together test but it may get merged in eventually.

**Comment by danielchalef** [comment]
It appears stock kaldi only uses the GPU for model training, and not transcription.

**Comment by danielchalef** [comment]
Optimizing OpenBLAS (TARGET= and GCC -mtune) and Kaldi (GCC -mtune) for my CPU architecture (bdver1) yielded a 25% performance improvement (17 seconds to 12 seconds). Unfortunately still too slow for use.

**Comment by tnga** [comment]
@danielchalef  I'm agreed with you! I’m student in university of Dschang in Cameroon; I planned to develop an IPA for linux which will be specially adapted for our african contest and generally in other contest according to people’s contributions. However, when Sirius has been published, i have decided to better use that great work and provide an intuitive interface like __cortana__ or __siri__  for common users and an intégration in GNU/Linux distributions which will be firstly promoted with next release of [this custom Ubuntu like system](http://umiproject.sf.net) that i have initiated to promote open source in my country. Sirius was one of my subjects for a meet-up this year. Skipping details, the difficulties now is ressources that is need to use sirius. For a student is not evident, and unless they provide a way to use their server in this case i will try an other way. Though internet connection’s penetration isn’t very considerable in country like mine. [Ila project](https://sites.google.com/site/ilavoiceassistant/) is going up but not now really open source and extensible for other purpose. I stay tune for now.

**Comment by saijel** [comment]
Hi @HarveyLiuFly,  please open a new issue if this problem still persists. Thanks!
