### ISSUE TITLE
where is libfst.so?

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [claritylab/lucida#57]
Finished building, I try to run but i get

./start-asr-server.sh  
Starting server on localhost:8081, use <Ctrl-C> to stop
..//src/online2bin/online2-wav-nnet2-latgen-faster: error while loading shared libraries: libfst.so.1: cannot open shared object file: No such file or directory
^CTraceback (most recent call last):
  File "./start-asr-dnn-server.py", line 82, in <module>
    server.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 236, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 155, in _eintr_retry
    return func(*args)
KeyboardInterrupt

**Comment by yqzhang** [comment]
It is supposed to be built inside `sirius/sirius-application/speech-recognition/tools/`, but there are some bugs preventing the kaldi binary from linking against it. We are working on a fix.
Thanks for letting us know!

**Comment by clairebaby** [comment]
I meet this same problem, have you solved it, and how?

**Comment by saijel** [comment]
Hi @Alessandro-Barbieri,  please open a new issue if this problem still persists. Thanks!
