### ISSUE TITLE
libtool not found 

### ISSUE THREAD

**Issue by jeje-50** [claritylab/lucida#58]
I'm trying to build sirius on debian and I found something strange when I build kaldi tools.

After decompress tools.tar.gz, I'm trying to launch 'make' and I had this :

`root@sirius:/home/sirius/sirius-application/speech-recognition/kaldi/tools# make`
`extras/check_dependencies.sh`
`extras/check_dependencies.sh: libtool is not installed.`
`extras/check_dependencies.sh: we recommend that you run (our best guess):`
`sudo apt-get install  libtool`

APT say it's already installed :
`apt-get install  libtool`
`libtool is already the newest version.`

I looked the file "extras/check_dependencies.sh" and you use 'which' to check if packages are installed.
In my config "which libtool" doesn't return something so the script stops.

I remove "libtool" of the check list and all running yet (yes it's dirty !)

`for f in make automake autoconf patch awk grep bzip2 gzip wget git; do`
`if ! which $f >&/dev/null; then`
`echo "$0: $f is not installed."`
`add_packages $f $f`
`fi`
`done`

I don't known if it's a bug but I report-it if I can help someone 

:)

**Comment by Waxo** [comment]
This script is from kaldi. I had the same problem. Your "fix" gain me some time. Thanks

**Comment by A4d1l** [comment]
How did you resolve the issue??

**Comment by jeje-50** [comment]
I just install libtool and remove libtool from list of check in script "check_dependencies.sh"

**Comment by saijel** [comment]
Hi @jeje-50, please open a new issue if this problem still persists. Thanks!
