### ISSUE TITLE
SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by OSS542** [claritylab/lucida#60]
bash-3.2$ git clone https://github.com/jhauswald/sirius.git
Cloning into 'sirius'...
error: SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed while accessing https://github.com/jhauswald/sirius.git/info/refs
fatal: HTTP request failed

**Comment by OSS542** [comment]
using "GIT_SSL_NO_VERIFY=true git clone https://github.com/jhauswald/sirius.git" works around this, so it appears that either the cert is invalid, or the validation is not working for some reason.

**Comment by khornberg** [comment]
Can you clone other Github repos?

**Comment by saijel** [comment]
Hi @OSS542, please open a new issue if this problem still persists. Thanks!
