### ISSUE TITLE
Virtual Box image to use sirius ?

### ISSUE THREAD

**Issue by ychoucha** [claritylab/lucida#61]
Hello,

can u have an virtualbox image to use sirius please ?

because to install it it's really long, and not easy.

thanks to you

**Comment by jbeuckm** [comment]
+1

**Comment by Timopheym** [comment]
https://groups.google.com/forum/#!topic/sirius-users/9xJ55yJpVZ8 - there is some... but it is 60 GB... 0_O

Now i am making my own based on Ubuntu server x64 10.04, if someone wants i can give it after setup i guess it should be a bit less (30 GB?). But i would like to setup Vagrant environment where the software does run on Virtual Machine and the codebase could be hosted on main machine (with transparent mapping). 

What do you think about that, has anyone such experience?  (i have this setup in my company, and i like it.)

**Comment by jhauswald** [comment]
Included in #104 and check out http://lucida.ai for a virtualbox!
