### ISSUE TITLE
libindri_jni.so: wrong ELF class: ELFCLASS64 and not existing /wiki_indri_index/manifest

### ISSUE THREAD

**Issue by MaciekLeks** [claritylab/lucida#62]
I use 32bit Lubuntu (Ubuntu) 14.04 on 64bit machine. After launching start-qa-server.sh I get the exeption from the issue title. I think that libindri_jni.so is compiled for the 64bit OS. I guess the file is not compiled during Sirius installation, because the date of the file is before the installation process on my OS.

**Comment by MaciekLeks** [comment]
I have downloaded indri-5.8 and then I followed the instructions:
1. ./configure CFLAGS="-g -O3 -m32" CXXFLAGS="-g -O3 -m32" --enable-java --with-javahome=<JDK_JAHA_HOME> --prefix=<OUT_LIB_PATH>
2. make
3. make all  install

Then I replaced old libindri_jni.so by a new one. 
After feeding the server (start-qa-server.sh) by some sample query I got the exception:

*Search error:
java.lang.Exception: ../src/Repository.cpp(435): Couldn't open a repository in read-only mode at '/home/user/Documents/sirius/sirius-application/question-answer/wiki_indri_index/' because:
	../src/Parameters.cpp(469): Couldn't open parameter file '/home/user/Documents/sirius/sirius-application/question-answer/wiki_indri_index/manifest' for reading.
*

There is no manifest file in the wiki_indri_folder... What should I do?

**Comment by Timopheym** [comment]
@MaciekLeks Thanks you very much - your tip helped me, imoprtant to not forget to set --with-javahome= and  --prefix= params 
--with-javahome=/usr/lib/jvm/java-7-openjdk-i386/ --prefix=`pwd` in my case.
i didn't get java.lang.Exception: ../src/Repository.cpp error becorse i do have manifest file 
 ```cat manifest```:
```xml 
<parameters>
	<field>
		<name>text</name>
	</field>
	<indexCount>3</indexCount>
	<indexes>
		<index>2</index>
	</indexes>
	<injectURL>true</injectURL>
	<normalize>true</normalize>
	<stemmer>
		<name>krovetz</name>
	</stemmer>
</parameters>
```

where did you get your wiki archive? try my manifest, thanks and good luck!

**Comment by MaciekLeks** [comment]
@Timopheym, thank you. Finally I've upgraded my linux to 64 bit version. Then, I carefully installed the whole wiki archive. At that time when I wrote the post something went wrong on my machine (disk quota) with the unpacked archive. So, ALL be very careful when unpacking the wiki tar... Now it works well.

**Comment by Timopheym** [comment]
Glad to know it. On on my old machine with 2GB RAM when i run voice
recognition and QA system it did hang totally (no even  capslock =)).
So i'll try on x64 virtual box with 4GB RAM, hope it will fine for that
monster +)

On Wed, May 20, 2015 at 11:32 AM, MaciekLeks <notifications@github.com>
wrote:

> @Timopheym <https://github.com/Timopheym>, thank you. Finally I've
> upgraded my linux to 64 bit version. Then, I carefully installed the whole
> wiki archive. At that time when I wrote the post something went wrong on my
> machine (disk quota) with the unpacked archive. So, ALL be very careful
> when unpacking the wiki tar... Now it works well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claritylab/sirius/issues/62#issuecomment-103807858>.
>



-- 
Kind regards,
Timophey Molchanov.

First do it, then do it right, then do it fast.

**Comment by zm594406222** [comment]
when i run ./start-qa-server.sh,an error below:
Search error:
java.lang.Exception: ../src/Repository.cpp(435): Couldn't open a repository in read-only mode at '/usr/local/sirius-1.0.1/sirius-application/question-answer/wiki_indri_index/' because:
	../src/File.cpp(130): Couldn't open for reading: /usr/local/sirius-1.0.1/sirius-application/question-answer/wiki_indri_index/collection/storage

Search failed.

thanks.

**Comment by saijel** [comment]
Hi @MaciekLeks, please open a new issue if this problem still persists. Thanks!
