### ISSUE TITLE
Splitting sirius in sub-gits

### ISSUE THREAD

**Issue by auguster** [claritylab/lucida#63]
I'm currently building sirius with a different machine for sirius-application and sirius-web.
I would be easier for me if you had splitted sirius in separate sub-git. The sources are quite important, it's a pain to pull it several times...

Maybe it's an improvement you should considered.

**Comment by d4ndo** [comment]
Good Idea. The web frontend should have its own repository. This way, it is very easy to include a sirius frontend on all kind of websites without having this big overhead. A Raspberry Pi could provide a frontend for people to use. sirius itself runs as a service on some other host.

For this case, I also have some suggestions:

a) The Quesition-Answering System uses HTTP GET to transfer sensible data. I would prefer HTTP POST.

b) It would be great to have some additional cgi-scripts written in python or PHP. Thus, the user can choose:

* sirius-application/run-scripts (python server)
* sirius-application/cgi-scripts (apache / nginx /lighttpd)(transport encryption already exists)

c) transport encryption from sirius-web and sirius-client to sirius.

d) /run-script or /cgi-script should have some kind of input validation to protect the services from e.G. SQL injection or similar.

Cheers

**Comment by auguster** [comment]
I tried to build sirius as a docker component but it's hell to build it, too many dependencies. Most of them are not taken into account in the get-dependencies.sh file. I'm not sure which version of OpenCV I can use. If 2.4.9 is fine I can just ``apt-get install libopencv-dev`` it...

I guess the suggestions should be in separated git issues as well ;)
For c) I guess you could put nginx in between your client and server to add an SSL layer.

**Comment by d4ndo** [comment]
I guess the problem with `OpenCV is, that it can be compiled in two ways. free and nonfree. sirius uses some nonfree components. Ubuntu or Debian packages distribute the free version. That is why opencv needs to be compiled to use sirius.

But the sirius-web component does not have many dependencies, does it?

  5 apt-get install -y python-pip python-pyaudio
  6 pip install wtforms Flask requests pickledb

Strange:
The web-sirius.py has some hard coded ip address to connect to sirius.
servers = ['141.xxx.xxx.xxx']

Cheers

**Comment by yunshengb** [comment]
Please pull the latest version, and see if the issues still remain. Thanks!

**Comment by saijel** [comment]
Hi @auguster, please open a new issue if this problem still persists. Thanks!
