### ISSUE TITLE
make-db.py can't find libopencv_highgui.so

### ISSUE THREAD

**Issue by wiseman** [claritylab/lucida#66]
On Ubuntu 14.10:

```
$ ./make-db.py landmarks matching/landmarks/db/
./match --build matching/landmarks/db/
./match: error while loading shared libraries: libopencv_highgui.so.2.4: cannot open shared object file: No such file or directory
```

This is documented at https://groups.google.com/forum/#!topic/sirius-users/i-FO0EzmBvU but I'm opening this here for more visibility.

The solution for now is to do this:

```
$ LD_LIBRARY_PATH=/usr/local/lib ./make-db.py landmarks matching/landmarks/db/
```

**Comment by saijel** [comment]
Hi @wiseman, please open a new issue if this problem still persists. Thanks!
