### ISSUE TITLE
Add support for incremental/"online" ASR

### ISSUE THREAD

**Issue by wiseman** [claritylab/lucida#67]
It's possible to significantly reduce the latency of ASR for systems that support it by doing incremental/"online" recognition: processing audio as it comes in.  Especially for interactive use (mobile apps, etc.) this can drastically improve the user experience.

For example, Kaldi calls ithis "online decoding" and the [documentation claims](http://kaldi.sourceforge.net/online_decoding.html) that "The program online2-wav-gmm-latgen-faster.cc is currently the primary example program for the GMM-based online-decoding setup. It reads in whole wave files but internally it processes them chunk by chunk with no dependency on the future".  Pocketsphinx supports something similar (though I think a tiny patch is required to give access to CMN priors).

There would be 2 steps to adding this:

1. Add the incremental processing to the ASR backends.
2. Support HTTP chunked-encoding so that clients can stream audio to the server as they receive it.

**Comment by yunshengb** [comment]
Please check out the latest version which uses web socket. Thank you!
