### ISSUE TITLE
Answer Accuracy

### ISSUE THREAD

**Issue by stephenkeep** [claritylab/lucida#68]
Hi All,

I have managed to get the server configured and answering questions using ./start-qa-server.sh. However, the accuracy of the answers seems quite poor, for example:

What is the capital city of France?
Luang Prabang

How many moons does Jupiter have?
9781151499646

How old is Hugh Jackman?
80 years

What language do they speak in France?
French Canadian

In all I asked 20 questions and sirius was able to answer 3 correctly. 

Does anyone else get the same results?
Is this to be expected?
How can I improve these results?
Does the formatting of the question help return more accurate answers?
Does the wikipedia corpus need some cleansing?

**Comment by Timopheym** [comment]
It's important to understand that sirius is more a combination of services. And quality of QA system is upon OpenEphyra. 
Next important thing that OpenEphyra is a framework so if you find that you can make it better it's very easy to tune (just read a bit about the whole QA procedure and a bit Java knowledge). May be we need to fill more patterns there (there is a difference between "What is the capital city of France?" and "What is the capital of France?").

**Comment by saijel** [comment]
Hi @stephenkeep, please open a new issue if this problem still persists. Thanks!
