### ISSUE TITLE
Wiki database access error : QA server

### ISSUE THREAD

**Issue by Check-mate** [claritylab/lucida#71]
When I try QA service an error occurred .
I can't access the database wikipedia extracted in the question-answer directory.
Here is the log of my error :
http://pastebin.com/GhYxN2RS

**Comment by yunshengb** [comment]
The QA service is updated so that it no longer uses Wikipedia. Please check out the latest version. Thanks!

**Comment by saijel** [comment]
Hi @Check-mate, please open a new issue if this problem still persists. Thanks!
