### ISSUE TITLE
Lemur Indri Parameters

### ISSUE THREAD

**Issue by vaethis** [claritylab/lucida#75]
Can someone provide an example of the parameters file they used to import wikipedia into Indri? Looking for something like: 
<parameters>
     <stemmer>  
       <name>krovetz</name>
     </stemmer>

```
 <corpus>
   <path>/path/to/collection1/</path>        
   <class>xml</class>
 </corpus>
 <corpus>
   <path>/path/to/collection2/</path>
   <class>trecweb</class>
 </corpus>

 <field><name>title</name></field>
 <field><name>date</name><numeric>true</numeric><parserName>DateFieldAnnotator</parserName></field> 
```

</parameters>

Am I close? How would I data/merge to the current into the current question-answer indri database?

**Comment by betzelelgalut** [comment]
hi, i am looking for the same thing. i am wanting to create repositories out of all the wiki datasets. 
also does anyone know how to train the AI, when it gives back the wrong answers?

**Comment by vaethis** [comment]
This was answered in #68 I think this project is defunct. :(
