### ISSUE TITLE
Project alive?

### ISSUE THREAD

**Issue by testman42** [claritylab/lucida#77]
Is this project still active?
Only two updates that did not happen 4 months ago are README updates.

**Comment by d4ndo** [comment]
It would be a great opportunity for the University of Michigan to take sponsorship for this project. Also to provide a Sirius service for the public.

That would make the University of Michigan attractive for highly talented scientists in the field AI.

**Comment by irl** [comment]
I am investigating the possibility of inclusion of Sirius in Debian. This issue concerns me as I would not like to be packaging software which is not actively maintained.

(Debian Bug is 782763. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=782763)

**Comment by jhauswald** [comment]
I've been working with a team of students through the summer and we're going to roll all the changes into the next iteration of Sirius end of August once I'm out from under this paper deadline (grad students still need to write papers...)

@irl it would be helpful if any of the changes you mention in #37 could be tracked somewhere, we can make sure to address them and get this process started. Feel free of course to fix to also submit PRs as you see fit.

**Comment by testman42** [comment]
It's September already

**Comment by irl** [comment]
Debian is currently dealing with a transition from GCC 4.x to GCC 5. I've not forgotten about Sirius but that is currently taking my attention.

**Comment by yunshengb** [comment]
Next generation will be released by the end of this summer! Wait for a basic but working demo website deployed using Kubernetes.
