### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by rusbear** [claritylab/lucida#78]
Does Sirius work with other languages in addition to English?

**Comment by olmerg** [comment]
I have the same question? which will be the way to support other lenguages?

**Comment by yunshengb** [comment]
You can add another QA engine into Lucida or replace the current one with your own. Read abd follow `Design Notes -- How to Add Your Own Service into Lucida?` of the top level readme.

**Comment by saijel** [comment]
Hi @rusbear, please open a new issue if your question is still relevant. Thanks!
