### ISSUE TITLE
ASR starting problem

### ISSUE THREAD

**Issue by manish7273** [claritylab/lucida#79]
i have an issue with ASR

./start-asr-server.sh
Starting server on localhost:8081, use <Ctrl-C> to stop
./server.sh: line 12: ..//src/online2bin/online2-wav-nnet2-latgen-faster: No such file or directory

**Comment by cdmeister** [comment]
You need to run the `get-kaldi.sh` script with will download the kaldi source code and then run the `compile-sirius-servers.sh`which will compile all of the different kinds of services
