### ISSUE TITLE
Problem while running the kernels

### ISSUE THREAD

**Issue by giovannioliveira** [claritylab/lucida#80]
Hi there! I'm trying to install Sirius for the first time. Followed the tutorial over http://sirius.clarity-lab.org/sirius-suite/ and seems until the step Building the Kernels everything seems to be right. First of all, I'm having to export Caffe and OpenCV path manually, else "make test" don't run. Not the problem yet. After run make test, a JSON output is echoed with Kernel description, as spected. But no output file is generated. These 4 lines are echoed with JSONs, maybe it has something to do with the problem:

diff: ../input/regex_slre.baseline: No such file or directory
diff: ../input/regex_slre.pthread: No such file or directory

diff: ../input/stem_porter.baseline: No such file or directory
diff: ../input/stem_porter.pthread: No such file or directory

Directory contents after run "make test":

drwxr-xr-x  5 me me 4096 Abr  1 03:06 crf
drwxr-xr-x  7 me me 4096 Jul 22 17:30 dnn-asr
-rw-r--r--  1 me me  164 Jul 22 17:28 exports
drwxr-xr-x  6 me me 4096 Abr  1 03:06 fd
drwxr-xr-x  6 me me 4096 Abr  1 03:06 fe
-rw-r--r--  1 me me  248 Abr  1 03:06 .gitignore
drwxr-xr-x  6 me me 4096 Abr  1 03:06 gmm
-rw-r--r--  1 me me  375 Abr  1 03:06 Makefile
-rwxr-xr-x  1 me me  158 Abr  1 03:06 prepare.sh
-rw-r--r--  1 me me 1024 Abr  1 03:06 README.md
-rw-r--r--  1 me me 1025 Jul 22 16:16 README.md.save
drwxr-xr-x  5 me me 4096 Abr  1 03:06 regex
drwxr-xr-x  2 me me 4096 Abr  1 03:06 scripts
drwxr-xr-x  6 me me 4096 Abr  1 03:06 stemmer
drwxr-xr-x  2 me me 4096 Jul 22 15:54 utils

I'm sure it's not a big deal, but still not able to solve. Thank you !

**Comment by jhauswald** [comment]
If you go into regex, `make clean` then `make test` should solve your issue and same for the other ones. You need to `make test` specifically.

Probably a better way to do this than by compiling `-DTESTING` into the code, I agree ;)

Let me know how that looks,

**Comment by giovannioliveira** [comment]
The problems related to export path was solved, but still no output is generated. I'm specting some binary to be generated at sirius-suite root directory, is this right ? I'm really sorry, but i didn't get what you mean with "Probably a better way to do this than by compiling -DTESTING".

This is the echo output that I get when run regex directory `make test`:
`make -s -C baseline test
{
	"kernel":"regular_expression",
	"abrv":"regex",
	"expressions": 100,
	"questions": 200,
	"regex_compile": 0.250000,
	"regex": 66.713000
}
make -s -C pthread test
{
	"kernel":"regular_expression",
	"abrv":"pthread_regex",
	"threads": 4,
	"expressions": 100,
	"questions": 200,
	"regex_compile": 0.099000,
	"pthread_regex": 41.291000
}`

This is the echo output that I get when run root directory `make test`:
`{
	"kernel":"gaussian_mixture_model",
	"abrv":"gmm",
	"gmm": 18.718000
}
{
	"kernel":"pthread_gaussian_mixture_model",
	"abrv":"pthread_gmm",
	"threads": 4,
	"pthread_gmm": 13.622000
}
{
	"kernel":"dnn_automatic_speech_recognition",
	"abrv":"dnn-asr",
	"model":"../model/asr.prototxt",
	"weights":"../model/asr.caffemodel",
	"in_features": 548,
	"dnn-asr": 1025.971000
}
{
	"kernel":"pthread_dnn_automatic_speech_recognition",
	"abrv":"pthread_dnn-asr",
	"threads": 4,
	"model":"../model/asr.prototxt",
	"weights":"../model/asr.caffemodel",
	"in_features": 548,
	"pthread_dnn-asr": 770.328000
}
{
	"kernel":"feature_extraction",
	"abrv":"fe",
	"rows": 2048,
	"columns": 2048,
	"fe": 2912.165000
}
{
	"kernel":"pthread_feature_extraction",
	"abrv":"pthread_fe",
	"threads": 4,
	"rows": 2048,
	"columns": 2048,
	"tile_height": 512,
	"tile_width": 512,
	"tile_overlap": 50,
	"tiling": 0.015000,
	"pthread_fe": 1541.478000
}
{
	"kernel":"feature_description",
	"abrv":"fd",
	"rows": 2048,
	"columns": 2048,
	"fe": 2642.116000,
	"fd": 9835.946000
}
{
	"kernel":"pthread_feature_description",
	"abrv":"pthread_fd",
	"threads": 4,
	"rows": 2048,
	"columns": 2048,
	"tile_height": 512,
	"tile_width": 512,
	"tile_overlap": 15,
	"tiling": 0.015000,
	"pthread_fe": 1119.980000,
	"pthread_fd": 4099.013000
}
{
	"kernel":"conditional_random_fields",
	"abrv":"crf",
	"sentences": 2012,
	"crf": 2206.171000
}
{
	"kernel":"pthread_conditional_random_fields",
	"abrv":"pthread_crf",
	"threads": 4,
	"sentences": 2012,
	"pthread_crf": 1290.561000
}
{
	"kernel":"regular_expression",
	"abrv":"regex",
	"expressions": 100,
	"questions": 200,
	"regex_compile": 0.250000,
	"regex": 67.065000
}
{
	"kernel":"regular_expression",
	"abrv":"pthread_regex",
	"threads": 4,
	"expressions": 100,
	"questions": 200,
	"regex_compile": 0.096000,
	"pthread_regex": 49.290000
}
{
	"kernel":"porter_stemming",
	"abrv":"stemmer",
	"words": 29401,
	"stemmer": 3.171000
}
{
	"kernel":"pthread_porter_stemming",
	"abrv":"pthread_stemmer",
	"threads": 4,
	"words": 29401,
	"pthread_stemmer": 2.967000
}`
 
Also, after try to check how works sirius-application i'm having some problems inside image-matching. When I try do `make`, I get an error in line 28: `#include "keypoints.pb.h"`. Also, in the next line is included "store_mat.pb.h", which isn't there too. I just found a ".proto" version of these two includes.

I've compiled the speech-recognition kernel and it works like a charm. I'm really excited with the project and as soon I understand its structure better, I'm going to use in some experimental applications and try to contribute with this. Thank you, sir.

**Comment by saijel** [comment]
Hi @giovannioliveira, please open a new issue if this problem still persists. Thanks!
