### ISSUE TITLE
Sirius Server Error unable to process speech and image matching

### ISSUE THREAD

**Issue by sanyaade-speechtools** [claritylab/lucida#83]
Hello everybody,

I have just installed Sirius on Ubuntu Server 15.04. Everthing went well and all the 3 servers were up and running including some command-line tests carried out.

The following problems were found:
1.) the image matching test seems to crash out
2.) Speech test (recorded and wave files also generates errors
dump code from the server is shown below:
' '
ValueError

ValueError: View function did not return a response
Traceback (most recent call last)

    File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__

    return self.wsgi_app(environ, start_response)

    File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app

    response = self.make_response(self.handle_exception(e))

    File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app

    response = self.full_dispatch_request()

    File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request

    response = self.make_response(rv)

    File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1566, in make_response

    raise ValueError('View function did not return a response')

    ValueError: View function did not return a response

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object
' '
The Server Machine details:
Dell PowerEdge 1950 Quad Core 2.5GHZ, 20GB RAM, 500GB HDD PERC-5,1 raid
O/S is Ubuntu Server 15.04
Graphic card is Onboard. No Sound Card installed on the Server.
The text input works very well :+1:  

Question:
1.) Can Sirius run on a real Server or does it have to be a desktop server type?
1.) Do I need graphic GPU e.g. Nvidia or Radion to be installed?
2.) Also do I need to installed a Sound Card?

I have included the URL below of the server still running and for you to give a try!
http://educateiot.com:8081/ 
![sirius web access-1](https://cloud.githubusercontent.com/assets/13922967/9592331/f212f7a6-5039-11e5-960b-e9e855c43fe3.png)

Hear from you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by jhauswald** [comment]
If this is still an issue, please open a new issue. To answer your original questions:

1.) Can Sirius run on a real Server or does it have to be a desktop server type? Yes it can
1.) Do I need graphic GPU e.g. Nvidia or Radion to be installed? Nope you don't sirius runs on the CPU.
2.) Also do I need to installed a Sound Card? Depends where you are running the frontend to capture audio. If the client is running on the same server desktop, than most likely.
