### ISSUE TITLE
How does Sirius learn new knowledge?

### ISSUE THREAD

**Issue by jbeuckm** [claritylab/lucida#85]
What mechanism is available to give feedback so that answers can improve?

**Comment by jinpengchina** [comment]
good question.

**Comment by EvanWieland** [comment]
+1

**Comment by ampaho** [comment]
+1B

**Comment by Timopheym** [comment]
I am afraid current QA system - OpenEphyra does not support this mechanism. You should write another QA thrift service that can provide it, f.e. based on Memory Artificial Neural Networks.

**Comment by jhauswald** [comment]
There's actually a PR #91 that aims to do this. A student I've been working with implemented a thrift service that takes in a link (html page, pdf, etc) and generates a new indri database that OE can then query. @Timopheym's idea is a good one for other QA services but this will be a solution for OE.

**Comment by jhauswald** [comment]
This is now merged in at https://github.com/claritylab/lucida/tree/master/lucida/learn
