### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by beew** [claritylab/lucida#86]
There was a thread in June questioning the status of Sirius. The dev answered in late July and promised the next iteration for late August but it is late October already
https://github.com/claritylab/sirius/issues/77

Meanwhile on the google group I read about some commercial project called Lucida Sirius reincarnated. Does it mean this project is no longer alive? I am no expert in religions but my understanding is that you can't reincarnate without being dead first.

https://groups.google.com/forum/#!forum/sirius-users

**Comment by Zeioth** [comment]
Personally I'm really hoping for someone to put everything on the cloud. Great things can be achieved from there.

**Comment by beew** [comment]
Well if the project is dead the developer can at least post a one sentence announcement instead of just disappear. How difficult is it to just log in and post one sentence like "We have terminate the this project, have a nice day."?

**Comment by Dual2Core** [comment]
The project was pretty awesome. That's a shame it's down...

**Comment by rhetr** [comment]
maybe [mycroft](https://mycroft.ai/) will offer something similar

**Comment by crazywolf132** [comment]
Hey guys, nice to meet you all. I am officially taking over this project, but it will be under http://github.com/crazywolf132/sirius/

I would love some help from you guys concerning this project. Have a nice day!

**Comment by Timopheym** [comment]
@rhetr mycroft looks promising, but i guess it will took a year them to opensource...
@crazywolf132 your repo now is empty. What roadmap do you have? I am interesting in ML, and AI systems, also i wonder we could make sirius setup much easier then now. Also i have a lot of experience in FrontEnd development - so we could create nice Sirius demo. What is your plans?

**Comment by EvanWieland** [comment]
@crazywolf132 Would love to help out. Please populate your repo tho. A good demo would be nice as well, as @rhetr suggested.

**Comment by crazywolf132** [comment]
@Timopheym The repo will have all the code as soon as it is done uploading... should not take too much longer. @EvanWieland We would love your help. We will try to get a demo up as soon as possible, once we work out the best way of doing that.

**Comment by Timopheym** [comment]
@crazywolf132 So, then please contact me do to discuss details about demo and future roadmap. 
My mail: timopheym [ а_t ] gmail.com 
skype: timopheym

**Comment by EvanWieland** [comment]
@crazywolf132 @Timopheym Does someone want to snag a Github Page?

**Comment by JeremyARussell** [comment]
@crazywolf132 Are you officially taking this over as a member of Clarity Labs or is this more you officially announcing an unofficial continuation?

**Comment by crazywolf132** [comment]
@JeremyARussell You choose what it is, they have totally given up on this project, and they do not even accept pull requests any-more. I am willing to help you guys out on that. If you are just going to criticize me for helping, then you all can just sit here waiting for something to happen when it never will. I am sorry for wasting my time trying to help this community

**Comment by EvanWieland** [comment]
In the spirit of open source, let's give the keys to @crazywolf132. Is it really open if you can't contribute? Why let such a great project die? I support the migration.

**Comment by d4ndo** [comment]
This would also be a nice task for https://openai.com
Maybe ask for support there.

sirius should be modular. On one side some restful API for clients like an android app or some web applikation or a unix command see (https://github.com/d4ndo/sirius-client)  and on the other side an API so algorithm can be replaced and added easily.

So maybe it is better to implement and describe a nice interface and let a lot of people write different GUIs.

**Comment by akuckartz** [comment]
Is there any fork which is maintained?

**Comment by JeremyARussell** [comment]
@crazywolf132 My apologies if it seemed I was criticizing you, that's not how I meant it to come across, I was just wondering if you were using the word "official" correctly or in a looser fashion..

I was actually road-mapping out a plan to relaunch Sirius myself as well considering how dead things got.. Personally I was debating on if I should continue with my plans and launch it or if I should just join up with you and any team you can get together..

On one hand competition is good anyways, on the other hand teamwork has it's place, I think I'll continue with my own plans and just sit back and see how you run the show for a bit before I contribute what I've already done though..

@d4ndo Modular is definitely something I was thinking as well, it's already set up as such considering it is an amalgamation of several different pieces of software, but a refactor is severely needed..

Not only that, but the setup and testing needs to be easier, the tutorials and videos leave much to be desired, there's limited documentation on exactly what all the components do and it relies heavily on someone already knowing a ton of the terminology and concepts surrounding AI. Personally I'd like a version of Sirius that let's nearly anyone with any programming experience jump in, contribute and most importantly learn, about everything that goes into creating an intelligent personal assistant from the ground up. 

That said Sirius was more of an afterthought suite of software put together for the purpose of figuring out what hardware it best for these kinds of applications, I don't blame Clarity Labs for not investing as much time into what was essentially an afterthought as everyone else might have wanted them to. In fact I'm just full of gratitude that they released it all to the public and got the ball rolling in the first place.

I picture a day where everyone has a personalized IPA that takes on their own personality traits (or even better yet, personality traits which balance against your own). It's certainly an ambitious vision, but it's one that requires ambitious people from all walks of life and scientific backgrounds to join in on. Which is the reason I see the move to a modular infrastructure and making it so jumping in as a beginner programmer will still allow you to make meaningful contributions to the project, as possibly the two most meaningful goals to accomplish.. From there, the rest is maintaining a great community and keeping the momentum going.

**Comment by Timopheym** [comment]
@JeremyARussell @crazywolf132 @d4ndo Guys,

First i see that we have some common goals:
 - Modularity (open interfaces that can easy replace different parts of the system to test-and-play new CV\NLP\... approaches)
 - Easy Install and Setup as @JeremyARussell said, and wrote in other issue - this can be much easier new people to come over.
 - Possibility to tweak common setting of the system even for 10 years old guy. I wanna to my little brother to have his own Personal Assistent.  

Also i bet my stack, each of us have some ideas to experiment - i wanna try to build in on NN's and train it on my BrainWaves and videorecorder system, @crazywolf132 told me about his AIML experements...

But first we need some documented framework, easy to use and extend. 

That's why i think that it's better to connect, share our Roadmaps, and try to build something together. That's is opensource, right?

About OpenAI and mycroft - they are looking promising, but it will take years, then they will publish something working... personally me wanna have some developer experience in this area, before they gave me something.

What do you think?

**Comment by EvanWieland** [comment]
@Timopheym +1 to all that.

**Comment by Timopheym** [comment]
@JeremyARussell @crazywolf132 @d4ndo @EvanWieland and if we connecting to continue this project,i think we should write an email to all guys from claritylab about this - this would be right.

**Comment by wathek** [comment]
@Timopheym I'm also interested in this project and I'd like to contribute too.

**Comment by EvanWieland** [comment]
@Timopheym Yeah that's prolly the good, courteous thing to do.

**Comment by JeremyARussell** [comment]
@Timopheym I find myself agreeing a hundred percent. I still think good competition among open source forks can be a great thing, nothing would be stopping anyone from using each other's forks to enhance one another, but you're completely right. If all our project goals align to form the same project, it would be best if we figure out a productive way to cooperate and bounce idea's off each other.. The only thing I can think of at the moment that would require separate projects would be if their aims were completely different. So far it seems we're all on board with the same rough idea's though..

Also, I totally second the idea of us getting together in a hipchat or slack or something, and figuring out what our individual goals are, then forming a management structure and writing out an open letter to Clarity Labs to see if we can possibly get some official support.

**Comment by Timopheym** [comment]
@JeremyARussell i was thinking right about it. I like slack more.

**Comment by JeremyARussell** [comment]
@Timopheym Want to start a room for us? Or should we wait and let @crazywolf132 pop in and let us know what he thinks so far? It looks like he's probably at work or something seeing as he hasn't popped in yet this morning.. I'd hate to jump forward too much without his input, especially since this'll be a joint venture from the start..

**Comment by wathek** [comment]
@JeremyARussell, @Timopheym I think it's better to wait for @crazywolf132 to pop in and know what he thinks about all this.

**Comment by Timopheym** [comment]
@JeremyARussell i was speaking with him yesterday, he is for Australia and probably asleep now.
I've created a chat https://siriusai.slack.com/ - but you should give me your emails to invite there.
I agree that we should have a talk with @crazywolf132 so, let's go there, and wait answer form @crazywolf132 when he will have time to discuss all details.

**Comment by JeremyARussell** [comment]
@wathek, Yeah I would certainly feel more comfortable waiting to see what he thinks as well..

**Comment by JeremyARussell** [comment]
@Timopheym I see, yeah he's probably asleep being on the other side of the planet and all :p 

my email is jeremyarussell [a.t] gmail  dot  com

**Comment by Timopheym** [comment]
@crazywolf132 @d4ndo @EvanWieland @wathek   My mail: timopheym [ а_t ] gmail.com  send me yours there or post it here - i'll send invitation.

**Comment by wathek** [comment]
@Timopheym my email is wathek [a_t] gmail.com

**Comment by EvanWieland** [comment]
@Timopheym Sent you my email.

**Comment by Timopheym** [comment]
@EvanWieland @wathek youp.

**Comment by virtadpt** [comment]
:+1: to the relaunch, @crazywolf132.  I'm willing to hammer on Sirius pretty hard to see where it breaks down.

**Comment by Timopheym** [comment]
We plan to have a talk in slack ( https://siriusai.slack.com/ ) about the fork here - http://doodle.com/poll/aznr2c7d3ue9r8ap please send me\post your email to join.

**Comment by arunbahl** [comment]
@Timopheym Thanks for doing this - I’m adding my email to join the slack channel: arun [at] bridge.ai.


On December 17, 2015 at 11:55:18 AM, Timophey (notifications@github.com) wrote:

We plan to have a talk in slack ( https://siriusai.slack.com/ ) about the fork here - http://doodle.com/poll/aznr2c7d3ue9r8ap please send me\post your email to join.

**Comment by JeremyARussell** [comment]
Hey @arunbahl, I've gone ahead and added you to the slack team. See you there.

**Comment by JeremyARussell** [comment]
If anyone else wants or needs an invite I'll be online for another hour to provide them. Most of us are all over the planet so our hours are crazy and many are already asleep, we'll try and make sure we have enough admin's available to add people throughout the day though, and we'll certainly be able to get everyone situated when we get up in the morning as well.. We aren't talking anything about plans, but just getting to each other, what our experience is, why we're here, etc..

**Comment by crazywolf132** [comment]
@JeremyARussell  @Timopheym @virtadpt @wathek @EvanWieland Look. This is the first and last time I am saying it. I have set-up the project over at https://github.com/claritylab/sirius. My goal with this project is to help make it so modular, that in the not so distant future, we will be able to add this to a device and create our own personal assistants. I would like it to be so easy to install, that you literally just do one click and then you can name it. With AIML files, we might even be able to add a chat to it. So then it can interact with humans at a more "humanly" level than just searching. I would also like to get it to the point where we could develop a product where it can be linked to your house, and once again... use AIML files to have conversations with people. If you guys are wanting a real AI... check out my REAL AI that is made in JavaScript that learns things you teach it, and responds how an AI would. If you want something more like a ChatBot, come and look, I have another project where it demonstrates how AIML files work... and what they can be used for. I would love for you guys to come and join me over there.

Kind regards,
                    CrazyWolf @ ELECLOUD

**Comment by mlaurenzano** [comment]
I'm one of the original Sirius developers, and its exciting to see so much interest being rekindled in the project! I'd like to join in on the discussions on slack. michael.laurenzano --- a.t --- gmail.com

**Comment by crazywolf132** [comment]
@JeremyARussell @Timopheym @virtadpt @wathek @EvanWieland sorry, i meant https://github.com/crazywolf132/sirius

**Comment by wathek** [comment]
@crazywolf132 do you have a link to your other project with AIML ?

**Comment by fpemud** [comment]
@Timopheym my email is fpemud@sina.com.


I'm writing sirius ebuild for Gentoo Linux, which would make sirius installation like a breeze. It would be a help for other distros as well.
sirius has a lot of dependencies so my pace is relatively slow.
The ebuilds are in [my overlay](https://github.com/fpemud/fpemud-overlay)

**Comment by JeremyARussell** [comment]
@mlaurenzano  and @fpemud I went ahead and invited you guys to the chatroom.. I'll be in most of the day sporadically..

**Comment by crazywolf132** [comment]
@wathek please join the chat, as i am talking about it there.

**Comment by d4ndo** [comment]
Has someone created an IRC channel?. 

Or was this whole thing some troll attempt ?

**Comment by JeremyARussell** [comment]
@d4ndo We have a slack channel, shoot me your email and I'll invite you on up..

**Comment by JeremyARussell** [comment]
Great news everybody! The Sirius project isn't dead (well, not exactly). It's been re-branded as Lucida and development will be starting again full force ahead.The focus of the project will be on building Lucida into a modular, extensible open source intelligent assistant platform.

        The goal is to make it so that any individual Lucida component can be swapped out for another one. In addition to the ability to swap out individual parts of the platform, the modular design of Lucida will help facilitate a build-your-own virtual assistant ecosystem. In essence, it will eventually be possible to run a bare minimum version of Lucida. Only want the QA system? We got you there. Only want to run speech recognition? That's fine too. Want to run a robust AI, with all the fixins and add-ons? Have at it.

        When Sirius was started it was more of an afterthought prototype for research done on what hardware platforms work best for an IPA (Intelligent Personal Assistant), it seemed that a re-brand would be a good idea once it was decided to focus on the AI platform itself.  We hope everyone enjoys the new update, and joins us in fostering the software and community around Lucida to turn it into the open intelligent assistant ecosystem the world deserves.

**Comment by jkerak** [comment]
@JeremyARussell junior-ish developer here, looking to get involved, and interested in this project... send me a slack invite? 

jkerak 

 --- a.t --- gmail.com

**Comment by JeremyARussell** [comment]
@jkerak Alright, invitation sent.. See you there if you get on in the next hour or so.

**Comment by cdmeister** [comment]
Hey  I was wondering if I could get an invite for the slack channel. I was one of the students that worked on Lucida over the summer that port it over into Thrift. Particularly I worked on the thrift interface for ASR

**Comment by jhauswald** [comment]
Done.

**Comment by yunshengb** [comment]
Lucida is migrating to the next version. Wait for a demo website by the end of this summer, or look at the ```dev``` branch!

**Comment by Kezryk** [comment]
Sirius was Renamed to Lucida Because of a Cease and desist order from Apple, who has a copyright on the name. Lucida is a product of university of michigan. and IS the backend to Clinc, a Personal finance assistant. Is it dead who knows. But it is a start.
