### ISSUE TITLE
in ./image-matching directory,run make...

### ISSUE THREAD

**Issue by zm594406222** [claritylab/lucida#94]
root@zm-Lenovo:/usr/local/sirius-1.0.1/sirius-application/image-matching# make
g++ detect.o kp_protobuf.o keypoints.pb.cc store_mat.pb.cc -o match -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_nonfree -lopencv_flann -lopencv_objdetect -lopencv_features2d -lopencv_gpu -lrt -lboost_program_options -lboost_filesystem -lboost_system -lprotobuf -ltesseract
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_nonfree.so：对‘cv::ocl::integral(cv::ocl::oclMat const&, cv::ocl::oclMat&, int)’未定义的引用
collect2: error: ld returned 1 exit status
make: *** [match] 错误 1

**Comment by cdmeister** [comment]
seems like you  have an OpenCV issue. Did you install OpenCV from source or Ubuntu repository?

**Comment by yunshengb** [comment]
Please check out the latest version and build again. Thank you!
