### ISSUE TITLE
Docker-compose / Kubernetes

### ISSUE THREAD

**Issue by lucmichalski** [claritylab/lucida#96]
Hi guys,

Hope u are doing well !

Is there any docker-compose or kubernetes templates available for Lucida ?

That would be awesome !

Cheers,
Luc Michalski

**Comment by Timopheym** [comment]
Hey @lucmichalski there was one Docker file for sirius https://github.com/hoseoglee/sirius-docker i think it will be easy to edit it for Lucida, do you have an experience with docker?

**Comment by jhauswald** [comment]
As @Timopheym said, currently there isn't a docker image besides the start of that one. We'd love to have some help setting one up @lucmichalski.

**Comment by lucmichalski** [comment]
I am friend with the guy who coded docker :-)

I will create one if u want.

Have u ever considered to use http://iris.karalabe.com/ in order to get mixed query results with the surveyor/respondent pattern ? That would be awesome too for Lucida

**Comment by jhauswald** [comment]
Well sounds like you're (over)-qualified to take lead on this then :+1: 

And now we have not, I'll definitely take a look and relay it to the team I'm working with, thanks for the tip!

**Comment by lucmichalski** [comment]
Communication patterns are the first step to build a neuron... Lucida is all about that :-)

Keep u update for the dockerfile or docker-compose. I do not think that Lucida is ready for some Kubernetes templates for the moment until some proper routing rules could be setup (especially for the image matching if u want to go large scale).

**Comment by Timopheym** [comment]
I don't see C++ bindings for Iris actually.

On Tue, Jan 19, 2016 at 6:27 AM, Luc Michalski <notifications@github.com>
wrote:

> Communication patterns are the first step to build a neuron... Lucida is
> all about that :-)
>
> Keep u update for the dockerfile or docker-compose. I do not think that
> Lucida is ready for some Kubernetes templates for the moment until some
> proper routing rules could be setup (especially for the image matching if u
> want to go large scale).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claritylab/lucida/issues/96#issuecomment-172727250>.
>



-- 
Kind regards,
Timophey Molchanov.

First do it, then do it right, then do it fast.

**Comment by lucmichalski** [comment]
@Timopheym here is a couple of links using nanomsg (surveyor/respondent pattern) in cpp (using bond for serialization):

Repo: https://github.com/daniel-j-h/DistributedSearch/
Article: https://daniel-j-h.github.io/post/distributed-search-nanomsg-bond/

Some interesting go examples are available with iris at: https://github.com/ibmendoza/go-examples

Advantage of iris, name based discovery of services with clustering.

Initially, I was thinking to create a reverse proxy with Vulcand and create a middleware storing some distributed search logic in the Etcd store per routes.

**Comment by lucmichalski** [comment]
@Timopheym Here is an interesting repo for Image Matching allowing you to mix all the existing Features Descriptors/Detectors in c++ with an inverted search: https://github.com/introlab/find-object.

**Comment by Vitorbnc** [comment]
Hi,
I couldn't find an image on docker hub, is there one?

**Comment by lavvy** [comment]
Any kubernetes yaml yet

**Comment by yunshengb** [comment]
I am deploying the demo website for the next generation of Lucida on a university server. I am using Kubernetes and check out [this repo] (https://github.com/yunshengb/KuberLucida) for the Kubernetes scripts. They will be integrated into this repo by the end of this summer.

**Comment by yunshengb** [comment]
Check out `tools/deploy`. Thanks!
