### ISSUE TITLE
imserver doesn't use command line arguments as documentation states

### ISSUE THREAD

**Issue by ryanniehaus** [claritylab/lucida#98]
Ports are hard coded in imserver.  Command line arguments are currently ignored.
(I compiled the command center version under lucida/lucida/imm/lucida/)

Ports should be configurable (per README.md in that folder)

**Comment by cdmeister** [comment]
Yea we know about that. Nobody has gotten around to it. For args parsing, we want to use boost's program options to parse the args.

**Comment by jhauswald** [comment]
I've actually fixed some of these as I was building a docker for lucida https://github.com/jhauswald/lucida/commit/18b4f462186fdc866a380e932961242da89aa5d2. Once I'm done with that I'll push it to the master repo. Thanks for pointing it out!

**Comment by yunshengb** [comment]
Unfortunately. we no longer support command line argument for port. Ports are fixed for easy maintenance, because if you change the port, you have to also modify the configuration of the command center and the Kubernetes scripts. Thanks for understanding.
